/// The Madar icon system — SF-Symbol-style names, kept for the call sites
/// that still use them.
///
/// System v2 draws its own glyph set ([MadarGlyph], `glyphs.dart`): a 24
/// grid, a 2.5 stroke, duotone when active. New work names a [MadarGlyph]
/// directly. The SF-Symbol names below stay so the feature packages compile
/// while they migrate — and every name the v2 set covers is ROUTED to it by
/// [madarIconGlyphs], so an unmigrated screen already draws the new icon.
/// Only the names the set does not cover (food categories, a handful of
/// specialised marks) still fall through to Lucide.
library;

import 'package:design_system/src/glyphs.dart';
import 'package:design_system/src/tokens/dimens.dart';
import 'package:flutter/widgets.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

/// SF-Symbol name → Lucide glyph. `null` lookup = unmapped (caller draws
/// nothing rather than a wrong icon). Keep in sync with the natives'
/// `IconCatalog.kt` (generated by tool/gen-icons.sh).
const Map<String, IconData> madarIconCatalog = <String, IconData>{
  // Status & feedback.
  'bell': LucideIcons.bell,
  'pencil': LucideIcons.pencil,
  'bell.fill': LucideIcons.bellRing,
  'exclamationmark.circle': LucideIcons.circleAlert,
  'exclamationmark.triangle': LucideIcons.triangleAlert,
  'exclamationmark.triangle.fill': LucideIcons.triangleAlert,
  'exclamationmark.bubble': LucideIcons.messageSquareWarning,
  'xmark': LucideIcons.x,
  'xmark.circle': LucideIcons.circleX,
  'xmark.circle.fill': LucideIcons.circleX,
  'checkmark': LucideIcons.check,
  'checkmark.circle': LucideIcons.circleCheck,
  'checkmark.circle.fill': LucideIcons.circleCheckBig,
  'checkmark.seal': LucideIcons.badgeCheck,
  'checkmark.icloud': LucideIcons.cloudCheck,
  // Navigation & disclosure.
  'chevron.backward': LucideIcons.chevronLeft,
  'chevron.left': LucideIcons.chevronLeft,
  'chevron.forward': LucideIcons.chevronRight,
  'chevron.right': LucideIcons.chevronRight,
  'chevron.down': LucideIcons.chevronDown,
  'chevron.up': LucideIcons.chevronUp,
  'arrow.up': LucideIcons.chevronUp,
  'arrow.down': LucideIcons.chevronDown,
  'arrow.up.arrow.down': LucideIcons.arrowUpDown,
  'arrow.down.left': LucideIcons.arrowDownLeft,
  'arrow.up.right': LucideIcons.arrowUpRight,
  'arrow.up.circle': LucideIcons.circleArrowUp,
  'arrow.down.circle': LucideIcons.circleArrowDown,
  'arrow.right.circle': LucideIcons.circleArrowRight,
  'arrow.left.circle': LucideIcons.circleArrowLeft,
  // Refresh & sync.
  'arrow.triangle.2.circlepath': LucideIcons.refreshCw,
  'arrow.clockwise': LucideIcons.rotateCw,
  'icloud.and.arrow.up': LucideIcons.cloudUpload,
  // User & account.
  'person': LucideIcons.user,
  'person.fill': LucideIcons.user,
  'person.crop.circle.badge.clock': LucideIcons.circleUser,
  // Communication & messages.
  'text.bubble': LucideIcons.messageSquare,
  'envelope': LucideIcons.mail,
  'phone.fill': LucideIcons.phone,
  'mappin.and.ellipse': LucideIcons.mapPin,
  // Search & input.
  'magnifyingglass': LucideIcons.search,
  'qrcode': LucideIcons.qrCode,
  'qr': LucideIcons.qrCode,
  'lock': LucideIcons.lock,
  'lock.circle': LucideIcons.lock,
  'lock.open': LucideIcons.lockOpen,
  'delete.left': LucideIcons.delete,
  'line.3.horizontal': LucideIcons.menu,
  'line.3.horizontal.decrease.circle': LucideIcons.listFilter,
  'slider.horizontal.3': LucideIcons.slidersHorizontal,
  // Commerce & shopping.
  'cart': LucideIcons.shoppingCart,
  'bag.fill': LucideIcons.shoppingBag,
  'creditcard': LucideIcons.creditCard,
  'wallet': LucideIcons.wallet,
  'banknote': LucideIcons.banknote,
  'receipt': LucideIcons.receipt,
  'gift': LucideIcons.gift,
  'shippingbox': LucideIcons.package,
  // Business & settings.
  'building.2': LucideIcons.building2,
  'bank': LucideIcons.landmark,
  'building.columns': LucideIcons.landmark,
  'storefront': LucideIcons.store,
  'gearshape': LucideIcons.settings,
  'layers': LucideIcons.layers,
  'square.stack.3d.up.fill': LucideIcons.layers,
  'square.grid.2x2.fill': LucideIcons.grid2x2,
  'square.grid.2x2': LucideIcons.grid2x2,
  // Time & schedule.
  'clock': LucideIcons.clock,
  'clock.badge.checkmark': LucideIcons.clock,
  'clock.badge.exclamationmark': LucideIcons.clock,
  'clock.arrow.circlepath': LucideIcons.history,
  'history': LucideIcons.history,
  'calendar': LucideIcons.calendar,
  'calendar.days': LucideIcons.calendarDays,
  'timer': LucideIcons.timer,
  'hourglass': LucideIcons.hourglass,
  // Attendance & staffing.
  'house': LucideIcons.house,
  'sun.max': LucideIcons.sun,
  'person.2': LucideIcons.users,
  'briefcase': LucideIcons.briefcase,
  'umbrella': LucideIcons.umbrella,
  // Files & documents.
  'note.text': LucideIcons.fileText,
  'doc.text': LucideIcons.fileText,
  'printer': LucideIcons.printer,
  'trash': LucideIcons.trash2,
  'trash.fill': LucideIcons.trash2,
  'tray.full': LucideIcons.inbox,
  'tray': LucideIcons.inbox,
  'tray.and.arrow.down': LucideIcons.download,
  'rectangle.portrait.and.arrow.right': LucideIcons.logOut,
  // Semantic & misc.
  'plus': LucideIcons.plus,
  'minus': LucideIcons.minus,
  'plus.forwardslash.minus': LucideIcons.calculator,
  'list.bullet.rectangle': LucideIcons.list,
  'list.bullet': LucideIcons.list,
  'hand.raised': LucideIcons.hand,
  'sparkles': LucideIcons.sparkles,
  'heart.circle': LucideIcons.heart,
  'wifi': LucideIcons.wifi,
  'wifi.slash': LucideIcons.wifiOff,
  'bluetooth': LucideIcons.bluetooth,
  'bluetooth.connected': LucideIcons.bluetoothConnected,
  'bicycle': LucideIcons.bike,
  'iphone': LucideIcons.smartphone,
  'number': LucideIcons.hash,
  'tag': LucideIcons.tag,
  'tag.fill': LucideIcons.tag,
  'ellipsis.circle': LucideIcons.ellipsis,
  'ellipsis': LucideIcons.ellipsis,
  'star': LucideIcons.star,
  'link': LucideIcons.link,
  // Share / export (the natives' CSV-export glyph never made their catalog —
  // fixed here; the SF name maps to Lucide's tray-with-up-arrow).
  'square.and.arrow.up': LucideIcons.share,
  // Screen-orientation flip control (settings).
  'rotate.left': LucideIcons.rotateCcw,
  'rotate.right': LucideIcons.rotateCw,
  // Display & visualization.
  'circle': LucideIcons.circle,
  'largecircle.fill.circle': LucideIcons.circleDot,
  'rectangle.split.2x1': LucideIcons.columns2,
  'play.circle': LucideIcons.circlePlay,
  'chart.pie': LucideIcons.pieChart,
  // Food & beverage.
  'fork.knife': LucideIcons.utensilsCrossed,
  'cup.and.saucer': LucideIcons.coffee,
  'croissant': LucideIcons.croissant,
  // Catalog category icons (map to food assets).
  'cat.coffee': LucideIcons.coffee,
  'cat.mocha': LucideIcons.coffee,
  'cat.tea': LucideIcons.coffee,
  'cat.bakery': LucideIcons.croissant,
  'cat.lunch': LucideIcons.sandwich,
  'cat.icecream': LucideIcons.iceCreamCone,
  'cat.drink': LucideIcons.cupSoda,
  'cat.water': LucideIcons.glassWater,
  'cat.ice': LucideIcons.snowflake,
  'cat.matcha': LucideIcons.leaf,
};

/// SF-Symbol name → v2 glyph, for every name the set covers. [MadarIcon]
/// consults this first; only a miss falls through to [madarIconCatalog].
const Map<String, MadarGlyph> madarIconGlyphs = <String, MadarGlyph>{
  'bell': MadarGlyph.bell,
  'bell.fill': MadarGlyph.bell,
  'pencil': MadarGlyph.edit,
  'exclamationmark.circle': MadarGlyph.alertCircle,
  'exclamationmark.triangle': MadarGlyph.alertTriangle,
  'exclamationmark.triangle.fill': MadarGlyph.alertTriangle,
  'xmark': MadarGlyph.close,
  // The sign-in / open-shift screens' leading marks: the duotone set has a
  // glyph for each, so they no longer fall through to the thin Lucide face.
  'arrow.right.circle': MadarGlyph.chevronForward,
  'lock.open': MadarGlyph.lock,
  'person.crop.circle.badge.clock': MadarGlyph.user,
  'exclamationmark.bubble': MadarGlyph.alertCircle,
  'xmark.circle': MadarGlyph.xCircle,
  'xmark.circle.fill': MadarGlyph.xCircle,
  'checkmark': MadarGlyph.check,
  'checkmark.circle': MadarGlyph.checkCircle,
  'checkmark.circle.fill': MadarGlyph.checkCircle,
  'checkmark.seal': MadarGlyph.checkCircle,
  'chevron.backward': MadarGlyph.chevronBack,
  'chevron.forward': MadarGlyph.chevronForward,
  'chevron.down': MadarGlyph.chevronDown,
  'chevron.up': MadarGlyph.chevronUp,
  'arrow.up': MadarGlyph.arrowUp,
  'arrow.down': MadarGlyph.arrowDown,
  'arrow.down.left': MadarGlyph.arrowDownStart,
  'arrow.up.right': MadarGlyph.arrowUpEnd,
  'arrow.triangle.2.circlepath': MadarGlyph.refresh,
  'arrow.clockwise': MadarGlyph.refresh,
  'arrow.uturn.backward': MadarGlyph.undo,
  'person': MadarGlyph.user,
  'person.fill': MadarGlyph.user,
  'person.2': MadarGlyph.users,
  'text.bubble': MadarGlyph.note,
  'phone.fill': MadarGlyph.phone,
  'magnifyingglass': MadarGlyph.search,
  'qrcode': MadarGlyph.scan,
  'qr': MadarGlyph.scan,
  'lock': MadarGlyph.lock,
  'lock.circle': MadarGlyph.lock,
  'delete.left': MadarGlyph.backspace,
  'line.3.horizontal': MadarGlyph.menu,
  'slider.horizontal.3': MadarGlyph.settings,
  'cart': MadarGlyph.bag,
  'bag.fill': MadarGlyph.bag,
  'creditcard': MadarGlyph.card,
  'wallet': MadarGlyph.wallet,
  'banknote': MadarGlyph.banknote,
  'receipt': MadarGlyph.receipt,
  'gearshape': MadarGlyph.settings,
  'square.grid.2x2.fill': MadarGlyph.grid,
  'square.grid.2x2': MadarGlyph.grid,
  'clock': MadarGlyph.clock,
  'clock.badge.checkmark': MadarGlyph.clock,
  'clock.badge.exclamationmark': MadarGlyph.clock,
  'calendar': MadarGlyph.calendar,
  'calendar.days': MadarGlyph.calendar,
  'printer': MadarGlyph.printer,
  'trash': MadarGlyph.trash,
  'trash.fill': MadarGlyph.trash,
  'tray.full': MadarGlyph.inbox,
  'tray': MadarGlyph.inbox,
  'rectangle.portrait.and.arrow.right': MadarGlyph.signOut,
  'plus': MadarGlyph.plus,
  'minus': MadarGlyph.minus,
  'list.bullet.rectangle': MadarGlyph.list,
  'list.bullet': MadarGlyph.list,
  'sparkles': MadarGlyph.sparkle,
  'wifi': MadarGlyph.wifi,
  'wifi.slash': MadarGlyph.wifiOff,
  'bicycle': MadarGlyph.bike,
  'tag': MadarGlyph.tag,
  'tag.fill': MadarGlyph.tag,
  'ellipsis.circle': MadarGlyph.more,
  'ellipsis': MadarGlyph.more,
  'star': MadarGlyph.star,
  'circle': MadarGlyph.ring,
  'largecircle.fill.circle': MadarGlyph.radio,
  'flame': MadarGlyph.flame,
  'table': MadarGlyph.table,
  'globe': MadarGlyph.globe,
  'camera': MadarGlyph.camera,
  'percent': MadarGlyph.percent,
  'bookmark': MadarGlyph.bookmark,
  'square': MadarGlyph.square,
  'checkmark.square.fill': MadarGlyph.squareCheck,
};

/// Directional glyphs flip in RTL so chevrons point the right way (parity
/// with the natives' `iconMirror` / Swift `MadarIcon.mirror`).
const Map<String, String> _iconMirror = <String, String>{
  'chevron.right': 'chevron.left',
  'chevron.left': 'chevron.right',
  'chevron.forward': 'chevron.backward',
  'chevron.backward': 'chevron.forward',
  'arrow.right.circle': 'arrow.left.circle',
  'arrow.left.circle': 'arrow.right.circle',
};

/// Every catalog name, for the design-system gallery. Unmodifiable.
final List<String> debugCatalogNames = List<String>.unmodifiable(
  madarIconCatalog.keys,
);

/// True when the ambient layout direction is right-to-left (Arabic).
bool isRtlLayout(BuildContext context) =>
    Directionality.of(context) == TextDirection.rtl;

/// A back-navigation chevron pointing toward the leading edge: `‹` in LTR,
/// `›` in RTL (where the leading edge is on the right).
///
/// Flutter mirrors layout (Row order, directional padding) under RTL, but
/// plain-text glyphs are NOT mirrored — a hardcoded chevron points the wrong
/// way in Arabic. These helpers pick the glyph matching the active direction.
String backGlyph(BuildContext context) => isRtlLayout(context) ? '›' : '‹';

/// A trailing disclosure chevron pointing toward the trailing edge: `›` in
/// LTR, `‹` in RTL. See [backGlyph] for why this exists.
String disclosureGlyph(BuildContext context) =>
    isRtlLayout(context) ? '‹' : '›';

/// Renders the icon for an SF-Symbol-style [name], tinted and sized: the v2
/// glyph when [madarIconGlyphs] covers the name (it mirrors itself under
/// RTL), otherwise the Lucide glyph from [madarIconCatalog].
///
/// A `null` or unmapped [name] renders nothing ([SizedBox.shrink]) rather
/// than a wrong icon. New work should name a [MadarGlyph] and use
/// [MadarGlyphIcon] directly.
///
/// ```dart
/// MadarIcon('cart', tint: context.madarColors.accent)
/// ```
class MadarIcon extends StatelessWidget {
  /// Creates an icon for the SF-Symbol-style [name].
  const MadarIcon(
    this.name, {
    required this.tint,
    this.size = IconSize.md,
    super.key,
  });

  /// SF-Symbol-style catalog name (e.g. `"printer"`, `"checkmark.circle"`).
  /// `null` renders nothing.
  final String? name;

  /// Icon color.
  final Color tint;

  /// Icon side length. Defaults to [IconSize.md].
  final double size;

  @override
  Widget build(BuildContext context) {
    final name = this.name;
    if (name == null) return const SizedBox.shrink();
    final v2 = madarIconGlyphs[name];
    if (v2 != null) return MadarGlyphIcon(v2, size: size, color: tint);
    final resolved = isRtlLayout(context) ? (_iconMirror[name] ?? name) : name;
    final glyph = madarIconCatalog[resolved];
    if (glyph == null) return const SizedBox.shrink();
    return Icon(glyph, size: size, color: tint);
  }
}
