/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "hold")]
    Hold,
    #[serde(rename = "raise_price")]
    RaisePrice,
    #[serde(rename = "lower_price")]
    LowerPrice,
    #[serde(rename = "bundle")]
    Bundle,
    #[serde(rename = "remove")]
    Remove,
    #[serde(rename = "reformulate")]
    Reformulate,
    #[serde(rename = "monitor")]
    Monitor,

}

impl std::fmt::Display for Action {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Hold => write!(f, "hold"),
            Self::RaisePrice => write!(f, "raise_price"),
            Self::LowerPrice => write!(f, "lower_price"),
            Self::Bundle => write!(f, "bundle"),
            Self::Remove => write!(f, "remove"),
            Self::Reformulate => write!(f, "reformulate"),
            Self::Monitor => write!(f, "monitor"),
        }
    }
}

impl Default for Action {
    fn default() -> Action {
        Self::Hold
    }
}

