/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivationCode {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    /// The 8 digits. Shown while free; kept afterwards so the list reads.
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "expires_at")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "kind")]
    pub kind: models::DeviceKind,
    #[serde(
        rename = "label",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub label: Option<Option<String>>,
    #[serde(
        rename = "revoked_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub revoked_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "state")]
    pub state: models::ActivationCodeState,
    #[serde(
        rename = "used_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub used_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(
        rename = "used_by_device",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub used_by_device: Option<Option<uuid::Uuid>>,
}

impl ActivationCode {
    pub fn new(
        branch_id: uuid::Uuid,
        code: String,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        expires_at: chrono::DateTime<chrono::FixedOffset>,
        id: uuid::Uuid,
        kind: models::DeviceKind,
        state: models::ActivationCodeState,
    ) -> ActivationCode {
        ActivationCode {
            branch_id,
            code,
            created_at,
            expires_at,
            id,
            kind,
            label: None,
            revoked_at: None,
            state,
            used_at: None,
            used_by_device: None,
        }
    }
}
