/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddonSlot {
    #[serde(rename = "addon_type")]
    pub addon_type: String,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "is_required")]
    pub is_required: bool,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "label_translations")]
    pub label_translations: serde_json::Value,
    #[serde(rename = "max_selections", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_selections: Option<Option<i32>>,
    #[serde(rename = "menu_item_id")]
    pub menu_item_id: uuid::Uuid,
    #[serde(rename = "min_selections")]
    pub min_selections: i32,
}

impl AddonSlot {
    pub fn new(addon_type: String, created_at: chrono::DateTime<chrono::FixedOffset>, id: uuid::Uuid, is_required: bool, label_translations: serde_json::Value, menu_item_id: uuid::Uuid, min_selections: i32) -> AddonSlot {
        AddonSlot {
            addon_type,
            created_at,
            id,
            is_required,
            label: None,
            label_translations,
            max_selections: None,
            menu_item_id,
            min_selections,
        }
    }
}

