/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllowList {
    #[serde(rename = "payment_method_ids")]
    pub payment_method_ids: Vec<uuid::Uuid>,
    #[serde(rename = "restricted")]
    pub restricted: bool,
}

impl AllowList {
    pub fn new(payment_method_ids: Vec<uuid::Uuid>, restricted: bool) -> AllowList {
        AllowList {
            payment_method_ids,
            restricted,
        }
    }
}
