/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AnalyticsOrder : One order, reduced to the money that belongs to the order itself.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsOrder {
    /// Calendar day the order belongs to, in the branch's timezone. Derived from `created_at` — the SAME derivation the receipt's `order_ref` uses, so the date here always matches the date embedded in that reference.
    #[serde(rename = "business_date")]
    pub business_date: chrono::NaiveDate,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "discount_amount")]
    pub discount_amount: i32,
    #[serde(rename = "order_id")]
    pub order_id: uuid::Uuid,
    /// Per-shift sequence number shown on the POS.
    #[serde(rename = "order_number")]
    pub order_number: i32,
    /// The human-readable reference printed on the receipt (`<BRANCHCODE>-<YYMMDD>-<NNNN>`). Null for orders predating it.
    #[serde(
        rename = "order_ref",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub order_ref: Option<Option<String>>,
    /// The service charge added to this order, `0` where the branch charges none. This was a hard-coded `0` for every order — the field was published as if it meant something while a service charge did not exist. It does now, and this is it.
    #[serde(rename = "service_charge")]
    pub service_charge: i32,
    #[serde(rename = "status")]
    pub status: String,
    /// Piastres. Sum of the line items before discount and tax.
    #[serde(rename = "subtotal")]
    pub subtotal: i32,
    #[serde(rename = "tax_amount")]
    pub tax_amount: i32,
    /// `subtotal - discount_amount + service_charge + tax_amount`. Deliberately COMPUTED rather than read from `orders.total_amount`, which also carries the delivery fee — this figure is the order's own value and nothing else. Tips are excluded too (they are not part of `total_amount` in the first place).
    #[serde(rename = "total_amount")]
    pub total_amount: i32,
}

impl AnalyticsOrder {
    /// One order, reduced to the money that belongs to the order itself.
    pub fn new(
        business_date: chrono::NaiveDate,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        discount_amount: i32,
        order_id: uuid::Uuid,
        order_number: i32,
        service_charge: i32,
        status: String,
        subtotal: i32,
        tax_amount: i32,
        total_amount: i32,
    ) -> AnalyticsOrder {
        AnalyticsOrder {
            business_date,
            created_at,
            discount_amount,
            order_id,
            order_number,
            order_ref: None,
            service_charge,
            status,
            subtotal,
            tax_amount,
            total_amount,
        }
    }
}
