/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttendanceRecord {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "business_date")]
    pub business_date: chrono::NaiveDate,
    #[serde(
        rename = "check_in_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_in_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(
        rename = "check_in_distance_meters",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_in_distance_meters: Option<Option<f64>>,
    #[serde(
        rename = "check_in_latitude",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_in_latitude: Option<Option<f64>>,
    #[serde(
        rename = "check_in_longitude",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_in_longitude: Option<Option<f64>>,
    #[serde(
        rename = "check_in_method",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_in_method: Option<Option<String>>,
    #[serde(
        rename = "check_out_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_out_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(
        rename = "check_out_distance_meters",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_out_distance_meters: Option<Option<f64>>,
    #[serde(
        rename = "check_out_latitude",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_out_latitude: Option<Option<f64>>,
    #[serde(
        rename = "check_out_longitude",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_out_longitude: Option<Option<f64>>,
    #[serde(
        rename = "check_out_method",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub check_out_method: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(
        rename = "created_by",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_by: Option<Option<uuid::Uuid>>,
    #[serde(rename = "early_leave_minutes")]
    pub early_leave_minutes: i32,
    #[serde(
        rename = "edit_reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub edit_reason: Option<Option<String>>,
    #[serde(
        rename = "edited_by",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub edited_by: Option<Option<uuid::Uuid>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "is_manual")]
    pub is_manual: bool,
    #[serde(rename = "late_minutes")]
    pub late_minutes: i32,
    #[serde(
        rename = "notes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notes: Option<Option<String>>,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "overtime_minutes")]
    pub overtime_minutes: i32,
    #[serde(
        rename = "scheduled_end_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub scheduled_end_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(
        rename = "scheduled_start_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub scheduled_start_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
    #[serde(
        rename = "user_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_name: Option<Option<String>>,
    #[serde(
        rename = "work_shift_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub work_shift_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "work_shift_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub work_shift_name: Option<Option<String>>,
    #[serde(rename = "worked_minutes")]
    pub worked_minutes: i32,
}

impl AttendanceRecord {
    pub fn new(
        branch_id: uuid::Uuid,
        business_date: chrono::NaiveDate,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        early_leave_minutes: i32,
        id: uuid::Uuid,
        is_manual: bool,
        late_minutes: i32,
        org_id: uuid::Uuid,
        overtime_minutes: i32,
        status: String,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        user_id: uuid::Uuid,
        worked_minutes: i32,
    ) -> AttendanceRecord {
        AttendanceRecord {
            branch_id,
            business_date,
            check_in_at: None,
            check_in_distance_meters: None,
            check_in_latitude: None,
            check_in_longitude: None,
            check_in_method: None,
            check_out_at: None,
            check_out_distance_meters: None,
            check_out_latitude: None,
            check_out_longitude: None,
            check_out_method: None,
            created_at,
            created_by: None,
            early_leave_minutes,
            edit_reason: None,
            edited_by: None,
            id,
            is_manual,
            late_minutes,
            notes: None,
            org_id,
            overtime_minutes,
            scheduled_end_at: None,
            scheduled_start_at: None,
            status,
            updated_at,
            user_id,
            user_name: None,
            work_shift_id: None,
            work_shift_name: None,
            worked_minutes,
        }
    }
}
