/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttendanceSettings {
    #[serde(rename = "absence_deduction_days")]
    pub absence_deduction_days: f64,
    #[serde(rename = "auto_checkout_buffer_minutes")]
    pub auto_checkout_buffer_minutes: i32,
    #[serde(rename = "branch_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub branch_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "default_overtime_multiplier")]
    pub default_overtime_multiplier: f64,
    /// Whether an approved mid-shift permission or early departure is PAID by default. The approver may override it on any individual request.
    #[serde(rename = "excused_time_paid_default")]
    pub excused_time_paid_default: bool,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "late_deduction_tiers", deserialize_with = "Option::deserialize")]
    pub late_deduction_tiers: Option<serde_json::Value>,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "require_geofence")]
    pub require_geofence: bool,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "weekend_days")]
    pub weekend_days: Vec<i32>,
    #[serde(rename = "working_days_per_month")]
    pub working_days_per_month: f64,
}

impl AttendanceSettings {
    pub fn new(absence_deduction_days: f64, auto_checkout_buffer_minutes: i32, created_at: chrono::DateTime<chrono::FixedOffset>, default_overtime_multiplier: f64, excused_time_paid_default: bool, id: uuid::Uuid, late_deduction_tiers: Option<serde_json::Value>, org_id: uuid::Uuid, require_geofence: bool, updated_at: chrono::DateTime<chrono::FixedOffset>, weekend_days: Vec<i32>, working_days_per_month: f64) -> AttendanceSettings {
        AttendanceSettings {
            absence_deduction_days,
            auto_checkout_buffer_minutes,
            branch_id: None,
            created_at,
            default_overtime_multiplier,
            excused_time_paid_default,
            id,
            late_deduction_tiers,
            org_id,
            require_geofence,
            updated_at,
            weekend_days,
            working_days_per_month,
        }
    }
}

