/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AttendanceSummary : One employee's totals over a reporting window.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttendanceSummary {
    #[serde(rename = "absent_days")]
    pub absent_days: i64,
    #[serde(rename = "half_days")]
    pub half_days: i64,
    #[serde(rename = "late_days")]
    pub late_days: i64,
    #[serde(rename = "leave_days")]
    pub leave_days: i64,
    #[serde(rename = "present_days")]
    pub present_days: i64,
    #[serde(rename = "total_late_minutes")]
    pub total_late_minutes: i64,
    #[serde(rename = "total_overtime_minutes")]
    pub total_overtime_minutes: i64,
    #[serde(rename = "total_worked_minutes")]
    pub total_worked_minutes: i64,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
    #[serde(rename = "user_name")]
    pub user_name: String,
}

impl AttendanceSummary {
    /// One employee's totals over a reporting window.
    pub fn new(
        absent_days: i64,
        half_days: i64,
        late_days: i64,
        leave_days: i64,
        present_days: i64,
        total_late_minutes: i64,
        total_overtime_minutes: i64,
        total_worked_minutes: i64,
        user_id: uuid::Uuid,
        user_name: String,
    ) -> AttendanceSummary {
        AttendanceSummary {
            absent_days,
            half_days,
            late_days,
            leave_days,
            present_days,
            total_late_minutes,
            total_overtime_minutes,
            total_worked_minutes,
            user_id,
            user_name,
        }
    }
}
