/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditRow {
    #[serde(rename = "action")]
    pub action: String,
    #[serde(
        rename = "actor_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub actor_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "actor_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub actor_name: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "details", deserialize_with = "Option::deserialize")]
    pub details: Option<serde_json::Value>,
    #[serde(
        rename = "employee_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub employee_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "employee_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub employee_name: Option<Option<String>>,
    #[serde(rename = "entity")]
    pub entity: String,
    #[serde(
        rename = "entity_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub entity_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(
        rename = "period_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub period_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reason: Option<Option<String>>,
}

impl AuditRow {
    pub fn new(
        action: String,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        details: Option<serde_json::Value>,
        entity: String,
        id: uuid::Uuid,
    ) -> AuditRow {
        AuditRow {
            action,
            actor_id: None,
            actor_name: None,
            created_at,
            details,
            employee_id: None,
            employee_name: None,
            entity,
            entity_id: None,
            id,
            period_id: None,
            reason: None,
        }
    }
}
