/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AvailabilityOut {
    #[serde(rename = "branches")]
    pub branches: Vec<models::BranchAvailabilityOut>,
    #[serde(rename = "org_active")]
    pub org_active: bool,
}

impl AvailabilityOut {
    pub fn new(branches: Vec<models::BranchAvailabilityOut>, org_active: bool) -> AvailabilityOut {
        AvailabilityOut {
            branches,
            org_active,
        }
    }
}

