/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchAddonOverrideInput {
    #[serde(rename = "addon_item_id")]
    pub addon_item_id: uuid::Uuid,
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "is_available", skip_serializing_if = "Option::is_none")]
    pub is_available: Option<bool>,
    /// Branch price in piastres; null inherits the org default_price.
    #[serde(rename = "price_override", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub price_override: Option<Option<i32>>,
}

impl BranchAddonOverrideInput {
    pub fn new(addon_item_id: uuid::Uuid, branch_id: uuid::Uuid) -> BranchAddonOverrideInput {
        BranchAddonOverrideInput {
            addon_item_id,
            branch_id,
            is_available: None,
            price_override: None,
        }
    }
}

