/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchAvailabilityOut {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "channels")]
    pub channels: Vec<models::ChannelOverrideOut>,
    #[serde(rename = "sizes")]
    pub sizes: Vec<models::SizeOverrideOut>,
}

impl BranchAvailabilityOut {
    pub fn new(branch_id: uuid::Uuid, channels: Vec<models::ChannelOverrideOut>, sizes: Vec<models::SizeOverrideOut>) -> BranchAvailabilityOut {
        BranchAvailabilityOut {
            branch_id,
            channels,
            sizes,
        }
    }
}

