/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchComparison {
    #[serde(rename = "avg_order_value")]
    pub avg_order_value: i64,
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "branch_name")]
    pub branch_name: String,
    #[serde(rename = "revenue_by_method", deserialize_with = "Option::deserialize")]
    pub revenue_by_method: Option<serde_json::Value>,
    #[serde(rename = "total_orders")]
    pub total_orders: i64,
    #[serde(rename = "total_revenue")]
    pub total_revenue: i64,
    #[serde(rename = "void_rate_pct")]
    pub void_rate_pct: f64,
    #[serde(rename = "voided_orders")]
    pub voided_orders: i64,
}

impl BranchComparison {
    pub fn new(avg_order_value: i64, branch_id: uuid::Uuid, branch_name: String, revenue_by_method: Option<serde_json::Value>, total_orders: i64, total_revenue: i64, void_rate_pct: f64, voided_orders: i64) -> BranchComparison {
        BranchComparison {
            avg_order_value,
            branch_id,
            branch_name,
            revenue_by_method,
            total_orders,
            total_revenue,
            void_rate_pct,
            voided_orders,
        }
    }
}

