/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BranchSettingsInput {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "in_mall_close_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub in_mall_close_time: Option<Option<String>>,
    /// Optional per-channel discount ids (must be active discounts in the caller's org). `null` clears the channel's discount.
    #[serde(rename = "in_mall_discount_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub in_mall_discount_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "in_mall_enabled")]
    pub in_mall_enabled: bool,
    #[serde(rename = "in_mall_fee")]
    pub in_mall_fee: i32,
    #[serde(rename = "in_mall_open_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub in_mall_open_time: Option<Option<String>>,
    /// When false, in-mall orders are accepted without a device GPS location. Defaults to true so an omitting client keeps the location check on.
    #[serde(rename = "in_mall_require_location", skip_serializing_if = "Option::is_none")]
    pub in_mall_require_location: Option<bool>,
    #[serde(rename = "max_road_distance_meters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_road_distance_meters: Option<Option<i32>>,
    /// When false, the public checkout skips OTP for this branch. Defaults to true so an omitting client keeps verification on.
    #[serde(rename = "otp_required", skip_serializing_if = "Option::is_none")]
    pub otp_required: Option<bool>,
    #[serde(rename = "outside_close_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub outside_close_time: Option<Option<String>>,
    #[serde(rename = "outside_discount_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub outside_discount_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "outside_enabled")]
    pub outside_enabled: bool,
    #[serde(rename = "outside_open_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub outside_open_time: Option<Option<String>>,
    #[serde(rename = "pickup_close_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pickup_close_time: Option<Option<String>>,
    #[serde(rename = "pickup_discount_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pickup_discount_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "pickup_enabled", skip_serializing_if = "Option::is_none")]
    pub pickup_enabled: Option<bool>,
    #[serde(rename = "pickup_fee", skip_serializing_if = "Option::is_none")]
    pub pickup_fee: Option<i32>,
    #[serde(rename = "pickup_open_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pickup_open_time: Option<Option<String>>,
    #[serde(rename = "prep_time_minutes")]
    pub prep_time_minutes: i32,
    #[serde(rename = "umbrella_close_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub umbrella_close_time: Option<Option<String>>,
    #[serde(rename = "umbrella_discount_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub umbrella_discount_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "umbrella_enabled", skip_serializing_if = "Option::is_none")]
    pub umbrella_enabled: Option<bool>,
    #[serde(rename = "umbrella_fee", skip_serializing_if = "Option::is_none")]
    pub umbrella_fee: Option<i32>,
    #[serde(rename = "umbrella_open_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub umbrella_open_time: Option<Option<String>>,
}

impl BranchSettingsInput {
    pub fn new(branch_id: uuid::Uuid, in_mall_enabled: bool, in_mall_fee: i32, outside_enabled: bool, prep_time_minutes: i32) -> BranchSettingsInput {
        BranchSettingsInput {
            branch_id,
            in_mall_close_time: None,
            in_mall_discount_id: None,
            in_mall_enabled,
            in_mall_fee,
            in_mall_open_time: None,
            in_mall_require_location: None,
            max_road_distance_meters: None,
            otp_required: None,
            outside_close_time: None,
            outside_discount_id: None,
            outside_enabled,
            outside_open_time: None,
            pickup_close_time: None,
            pickup_discount_id: None,
            pickup_enabled: None,
            pickup_fee: None,
            pickup_open_time: None,
            prep_time_minutes,
            umbrella_close_time: None,
            umbrella_discount_id: None,
            umbrella_enabled: None,
            umbrella_fee: None,
            umbrella_open_time: None,
        }
    }
}

