/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkReviewPending {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "reason")]
    pub reason: String,
}

impl BulkReviewPending {
    pub fn new(id: i64, reason: String) -> BulkReviewPending {
        BulkReviewPending { id, reason }
    }
}
