/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BundleWithComponents {
    #[serde(rename = "available_from_date", skip_serializing_if = "Option::is_none")]
    pub available_from_date: Option<chrono::NaiveDate>,
    #[serde(rename = "available_from_time", skip_serializing_if = "Option::is_none")]
    pub available_from_time: Option<String>,
    #[serde(rename = "available_until_date", skip_serializing_if = "Option::is_none")]
    pub available_until_date: Option<chrono::NaiveDate>,
    #[serde(rename = "available_until_time", skip_serializing_if = "Option::is_none")]
    pub available_until_time: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<uuid::Uuid>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "description_translations", deserialize_with = "Option::deserialize")]
    pub description_translations: Option<serde_json::Value>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "image_url", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_translations", deserialize_with = "Option::deserialize")]
    pub name_translations: Option<serde_json::Value>,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "price")]
    pub price: i32,
    #[serde(rename = "status")]
    pub status: models::BundleStatus,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "branch_ids")]
    pub branch_ids: Vec<uuid::Uuid>,
    #[serde(rename = "components")]
    pub components: Vec<models::BundleComponentHydrated>,
    /// Sum of component costs × quantity, in piastres. `null` when any component cost is unknown (`cost_missing = true`) — an unknown cost is never 0.
    #[serde(rename = "computed_cost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub computed_cost: Option<Option<i64>>,
    #[serde(rename = "cost_missing")]
    pub cost_missing: bool,
}

impl BundleWithComponents {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, description_translations: Option<serde_json::Value>, id: uuid::Uuid, name: String, name_translations: Option<serde_json::Value>, org_id: uuid::Uuid, price: i32, status: models::BundleStatus, updated_at: chrono::DateTime<chrono::FixedOffset>, branch_ids: Vec<uuid::Uuid>, components: Vec<models::BundleComponentHydrated>, cost_missing: bool) -> BundleWithComponents {
        BundleWithComponents {
            available_from_date: None,
            available_from_time: None,
            available_until_date: None,
            available_until_time: None,
            created_at,
            created_by: None,
            description: None,
            description_translations,
            id,
            image_url: None,
            name,
            name_translations,
            org_id,
            price,
            status,
            updated_at,
            branch_ids,
            components,
            computed_cost: None,
            cost_missing,
        }
    }
}

