/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BundlePerformanceResponse {
    #[serde(rename = "component_popularity")]
    pub component_popularity: Vec<models::ComponentPopularity>,
    #[serde(rename = "gross_revenue")]
    pub gross_revenue: i64,
    #[serde(rename = "net_profit")]
    pub net_profit: i64,
    #[serde(rename = "sales_volume")]
    pub sales_volume: i64,
}

impl BundlePerformanceResponse {
    pub fn new(component_popularity: Vec<models::ComponentPopularity>, gross_revenue: i64, net_profit: i64, sales_volume: i64) -> BundlePerformanceResponse {
        BundlePerformanceResponse {
            component_popularity,
            gross_revenue,
            net_profit,
            sales_volume,
        }
    }
}

