/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BundleSuggestion {
    #[serde(rename = "association")]
    pub association: Box<models::BundleAssociation>,
    #[serde(rename = "bundle_cm", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bundle_cm: Option<Option<i64>>,
    /// All cost-derived fields are `None` when any component lacks cost data.
    #[serde(rename = "bundle_cost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bundle_cost: Option<Option<i64>>,
    #[serde(rename = "bundle_discount_pct")]
    pub bundle_discount_pct: f64,
    #[serde(rename = "bundle_items")]
    pub bundle_items: Vec<models::ItemKey>,
    #[serde(rename = "bundle_list_price")]
    pub bundle_list_price: i64,
    #[serde(rename = "bundle_margin_pct", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bundle_margin_pct: Option<Option<f64>>,
    #[serde(rename = "bundle_suggested_price")]
    pub bundle_suggested_price: i64,
    #[serde(rename = "explanation")]
    pub explanation: String,
    #[serde(rename = "focus_item")]
    pub focus_item: Box<models::ItemKey>,
    #[serde(rename = "forecast")]
    pub forecast: Box<models::BundleForecast>,
    #[serde(rename = "guard_clips")]
    pub guard_clips: Vec<models::GuardClip>,
    /// True ⟺ at least one component is cost-missing.
    #[serde(rename = "missing_costs")]
    pub missing_costs: bool,
}

impl BundleSuggestion {
    pub fn new(association: models::BundleAssociation, bundle_discount_pct: f64, bundle_items: Vec<models::ItemKey>, bundle_list_price: i64, bundle_suggested_price: i64, explanation: String, focus_item: models::ItemKey, forecast: models::BundleForecast, guard_clips: Vec<models::GuardClip>, missing_costs: bool) -> BundleSuggestion {
        BundleSuggestion {
            association: Box::new(association),
            bundle_cm: None,
            bundle_cost: None,
            bundle_discount_pct,
            bundle_items,
            bundle_list_price,
            bundle_margin_pct: None,
            bundle_suggested_price,
            explanation,
            focus_item: Box::new(focus_item),
            forecast: Box::new(forecast),
            guard_clips,
            missing_costs,
        }
    }
}

