/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BundlesRow : One combo or deal over the period.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BundlesRow {
    #[serde(rename = "cost")]
    pub cost: i64,
    /// True when any line's cost was unknown (`cost` then counts the known part).
    #[serde(rename = "cost_missing")]
    pub cost_missing: bool,
    /// The combo's menu item id, or the deal rule's id.
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// `combo` | `deal`.
    #[serde(rename = "kind")]
    pub kind: String,
    /// The same lines at their normal prices.
    #[serde(rename = "list_value")]
    pub list_value: i64,
    /// `(revenue − cost) / revenue` as a fraction string; `null` when revenue is 0.
    #[serde(
        rename = "margin",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub margin: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_translations")]
    pub name_translations: serde_json::Value,
    #[serde(rename = "orders")]
    pub orders: i64,
    /// A combo: Σ its parts' line_total + their add-ons. A deal: Σ the consumed lines' line_total (after the deal).
    #[serde(rename = "revenue")]
    pub revenue: i64,
    /// `list_value − revenue`.
    #[serde(rename = "saving")]
    pub saving: i64,
    /// Combo units (Σ header quantity, refunds netted) or deal applications (Σ times).
    #[serde(rename = "sold")]
    pub sold: i64,
}

impl BundlesRow {
    /// One combo or deal over the period.
    pub fn new(
        cost: i64,
        cost_missing: bool,
        id: uuid::Uuid,
        kind: String,
        list_value: i64,
        name: String,
        name_translations: serde_json::Value,
        orders: i64,
        revenue: i64,
        saving: i64,
        sold: i64,
    ) -> BundlesRow {
        BundlesRow {
            cost,
            cost_missing,
            id,
            kind,
            list_value,
            margin: None,
            name,
            name_translations,
            orders,
            revenue,
            saving,
            sold,
        }
    }
}
