/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelOverrideInput {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "is_available", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_available: Option<Option<bool>>,
    #[serde(rename = "menu_item_id")]
    pub menu_item_id: uuid::Uuid,
    #[serde(rename = "price_override", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub price_override: Option<Option<i32>>,
}

impl ChannelOverrideInput {
    pub fn new(branch_id: uuid::Uuid, channel: String, menu_item_id: uuid::Uuid) -> ChannelOverrideInput {
        ChannelOverrideInput {
            branch_id,
            channel,
            is_available: None,
            menu_item_id,
            price_override: None,
        }
    }
}

