/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChannelOverride : A branch's override of the org's toggles. `null` (or absent) inherits.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelOverride {
    #[serde(
        rename = "delivery",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub delivery: Option<Option<bool>>,
    #[serde(
        rename = "online",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub online: Option<Option<bool>>,
    #[serde(
        rename = "pos",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pos: Option<Option<bool>>,
    #[serde(
        rename = "qr",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub qr: Option<Option<bool>>,
}

impl ChannelOverride {
    /// A branch's override of the org's toggles. `null` (or absent) inherits.
    pub fn new() -> ChannelOverride {
        ChannelOverride {
            delivery: None,
            online: None,
            pos: None,
            qr: None,
        }
    }
}
