/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChannelToggles : The four sale channels' toggles, resolved: `pos` (the till), `qr` (the table QR menu), `online` (the storefront, all four delivery sub-channels) and `delivery` (aggregator apps; stored and returned, honoured by the future menu push). Every channel is on until the owner switches it off.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelToggles {
    #[serde(rename = "delivery", skip_serializing_if = "Option::is_none")]
    pub delivery: Option<bool>,
    #[serde(rename = "online", skip_serializing_if = "Option::is_none")]
    pub online: Option<bool>,
    #[serde(rename = "pos", skip_serializing_if = "Option::is_none")]
    pub pos: Option<bool>,
    #[serde(rename = "qr", skip_serializing_if = "Option::is_none")]
    pub qr: Option<bool>,
}

impl ChannelToggles {
    /// The four sale channels' toggles, resolved: `pos` (the till), `qr` (the table QR menu), `online` (the storefront, all four delivery sub-channels) and `delivery` (aggregator apps; stored and returned, honoured by the future menu push). Every channel is on until the owner switches it off.
    pub fn new() -> ChannelToggles {
        ChannelToggles {
            delivery: None,
            online: None,
            pos: None,
            qr: None,
        }
    }
}
