/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChartHint : A hint for how the result is best visualized. The frontend may override.
/// A hint for how the result is best visualized. The frontend may override.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChartHint {
    #[serde(rename = "table")]
    Table,
    #[serde(rename = "bar")]
    Bar,
    #[serde(rename = "line")]
    Line,
    #[serde(rename = "pie")]
    Pie,

}

impl std::fmt::Display for ChartHint {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Table => write!(f, "table"),
            Self::Bar => write!(f, "bar"),
            Self::Line => write!(f, "line"),
            Self::Pie => write!(f, "pie"),
        }
    }
}

impl Default for ChartHint {
    fn default() -> ChartHint {
        Self::Table
    }
}

