/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ClaimDecision : A claim decision: the labour limits the approved day now breaks (a long day, a short rest). A warning, never a block (RU-13, minor default M26).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClaimDecision {
    /// `approved` · `rejected`
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "warnings")]
    pub warnings: Vec<models::LabourWarning>,
}

impl ClaimDecision {
    /// A claim decision: the labour limits the approved day now breaks (a long day, a short rest). A warning, never a block (RU-13, minor default M26).
    pub fn new(status: String, warnings: Vec<models::LabourWarning>) -> ClaimDecision {
        ClaimDecision { status, warnings }
    }
}
