/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CloseTillPreview {
    #[serde(rename = "expected_cash")]
    pub expected_cash: i64,
    #[serde(
        rename = "last_till_warning",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_till_warning: Option<Option<Box<models::LastTillWarning>>>,
    #[serde(rename = "methods")]
    pub methods: Vec<models::CloseTillMethod>,
    #[serde(rename = "till")]
    pub till: Box<models::Till>,
}

impl CloseTillPreview {
    pub fn new(
        expected_cash: i64,
        methods: Vec<models::CloseTillMethod>,
        till: models::Till,
    ) -> CloseTillPreview {
        CloseTillPreview {
            expected_cash,
            last_till_warning: None,
            methods,
            till: Box::new(till),
        }
    }
}
