/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ComboSettingsWrite : `PUT /settings/combos`. `min_margin` is replaced (omitted or `null` = no warning); `channels`, when present, replaces the org-wide toggles.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComboSettingsWrite {
    #[serde(
        rename = "channels",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub channels: Option<Option<Box<models::ChannelToggles>>>,
    /// A fraction between \"0\" and \"1\", e.g. \"0.55\".
    #[serde(
        rename = "min_margin",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub min_margin: Option<Option<String>>,
}

impl ComboSettingsWrite {
    /// `PUT /settings/combos`. `min_margin` is replaced (omitted or `null` = no warning); `channels`, when present, replaces the org-wide toggles.
    pub fn new() -> ComboSettingsWrite {
        ComboSettingsWrite {
            channels: None,
            min_margin: None,
        }
    }
}
