/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComboSlotWrite {
    #[serde(rename = "choices")]
    pub choices: Vec<models::ComboChoiceWrite>,
    /// Pre-selected on the till and used for unpicked replays; must be one of the slot's choices (by id, or by its category).
    #[serde(
        rename = "default_item_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_item_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "default_size_label",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_size_label: Option<Option<String>>,
    /// The slot's id, to keep it on an edit; omit for a new slot.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<uuid::Uuid>>,
    /// Picks allowed (1–10, ≥ min).
    #[serde(rename = "max")]
    pub max: i32,
    /// Picks required (0–10). 0 = optional slot.
    #[serde(rename = "min")]
    pub min: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_translations", skip_serializing_if = "Option::is_none")]
    pub name_translations: Option<serde_json::Value>,
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<i32>,
}

impl ComboSlotWrite {
    pub fn new(
        choices: Vec<models::ComboChoiceWrite>,
        max: i32,
        min: i32,
        name: String,
    ) -> ComboSlotWrite {
        ComboSlotWrite {
            choices,
            default_item_id: None,
            default_size_label: None,
            id: None,
            max,
            min,
            name,
            name_translations: None,
            sort: None,
        }
    }
}
