/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Compare : Period-over-period comparison mode.
/// Period-over-period comparison mode.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Compare {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "previous_period")]
    PreviousPeriod,
    #[serde(rename = "previous_year")]
    PreviousYear,
}

impl std::fmt::Display for Compare {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::PreviousPeriod => write!(f, "previous_period"),
            Self::PreviousYear => write!(f, "previous_year"),
        }
    }
}

impl Default for Compare {
    fn default() -> Compare {
        Self::None
    }
}
