/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContextSettings {
    #[serde(rename = "absence_deduction_days")]
    pub absence_deduction_days: f64,
    #[serde(rename = "advance_cap_percent")]
    pub advance_cap_percent: f64,
    #[serde(rename = "holiday_multiplier")]
    pub holiday_multiplier: f64,
    #[serde(
        rename = "late_deduction_tiers",
        deserialize_with = "Option::deserialize"
    )]
    pub late_deduction_tiers: Option<serde_json::Value>,
    #[serde(rename = "overtime_day_multiplier")]
    pub overtime_day_multiplier: f64,
    #[serde(rename = "overtime_mode")]
    pub overtime_mode: String,
    #[serde(rename = "overtime_night_multiplier")]
    pub overtime_night_multiplier: f64,
    #[serde(rename = "period_start_day")]
    pub period_start_day: i32,
    /// The business saved its rules; nobody clocks in before (RU-1, DSH-6).
    #[serde(rename = "rules_saved")]
    pub rules_saved: bool,
}

impl ContextSettings {
    pub fn new(
        absence_deduction_days: f64,
        advance_cap_percent: f64,
        holiday_multiplier: f64,
        late_deduction_tiers: Option<serde_json::Value>,
        overtime_day_multiplier: f64,
        overtime_mode: String,
        overtime_night_multiplier: f64,
        period_start_day: i32,
        rules_saved: bool,
    ) -> ContextSettings {
        ContextSettings {
            absence_deduction_days,
            advance_cap_percent,
            holiday_multiplier,
            late_deduction_tiers,
            overtime_day_multiplier,
            overtime_mode,
            overtime_night_multiplier,
            period_start_day,
            rules_saved,
        }
    }
}
