/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMarketingLinkRequest {
    #[serde(rename = "custom_slug", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_slug: Option<Option<String>>,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "path")]
    pub path: String,
}

impl CreateMarketingLinkRequest {
    pub fn new(label: String, path: String) -> CreateMarketingLinkRequest {
        CreateMarketingLinkRequest {
            custom_slug: None,
            label,
            path,
        }
    }
}

