/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBundleRequest {
    #[serde(rename = "available_from_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub available_from_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "available_from_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub available_from_time: Option<Option<String>>,
    #[serde(rename = "available_until_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub available_until_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "available_until_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub available_until_time: Option<Option<String>>,
    #[serde(rename = "branch_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub branch_ids: Option<Option<Vec<uuid::Uuid>>>,
    #[serde(rename = "components")]
    pub components: Vec<models::CreateBundleComponentInput>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "description_translations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description_translations: Option<Option<serde_json::Value>>,
    #[serde(rename = "image_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_translations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name_translations: Option<Option<serde_json::Value>>,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "price")]
    pub price: i32,
}

impl CreateBundleRequest {
    pub fn new(components: Vec<models::CreateBundleComponentInput>, name: String, org_id: uuid::Uuid, price: i32) -> CreateBundleRequest {
        CreateBundleRequest {
            available_from_date: None,
            available_from_time: None,
            available_until_date: None,
            available_until_time: None,
            branch_ids: None,
            components,
            description: None,
            description_translations: None,
            image_url: None,
            name,
            name_translations: None,
            org_id,
            price,
        }
    }
}

