/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateFloorTableRequest {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "height", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub height: Option<Option<f64>>,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "pos_x", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pos_x: Option<Option<f64>>,
    #[serde(rename = "pos_y", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pos_y: Option<Option<f64>>,
    #[serde(rename = "rotation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rotation: Option<Option<f64>>,
    #[serde(rename = "seats", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub seats: Option<Option<i32>>,
    #[serde(rename = "section_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub section_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "shape", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shape: Option<Option<String>>,
    #[serde(rename = "width", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub width: Option<Option<f64>>,
}

impl CreateFloorTableRequest {
    pub fn new(branch_id: uuid::Uuid, label: String) -> CreateFloorTableRequest {
        CreateFloorTableRequest {
            branch_id,
            height: None,
            label,
            pos_x: None,
            pos_y: None,
            rotation: None,
            seats: None,
            section_id: None,
            shape: None,
            width: None,
        }
    }
}

