/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCustomerRequest {
    /// The branch where the customer was added (a till sends its own).
    #[serde(
        rename = "branch_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub branch_id: Option<Option<uuid::Uuid>>,
    /// Client-minted id; a repeat with the same id returns the stored customer.
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<uuid::Uuid>>,
    /// DEPRECATED and ignored: a membership shares the customer's id, so there is nothing to link. Accepted so deployed tills keep working.
    #[serde(
        rename = "loyalty_customer_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub loyalty_customer_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "notes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notes: Option<Option<String>>,
    #[serde(
        rename = "phone",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone: Option<Option<String>>,
    /// Where the customer came from. Defaults to `pos` when a branch is named (a till) and `dashboard` otherwise.
    #[serde(
        rename = "source",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source: Option<Option<String>>,
}

impl CreateCustomerRequest {
    pub fn new(name: String) -> CreateCustomerRequest {
        CreateCustomerRequest {
            branch_id: None,
            id: None,
            loyalty_customer_id: None,
            name,
            notes: None,
            phone: None,
            source: None,
        }
    }
}
