/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CredentialSummary {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "branch_name")]
    pub branch_name: String,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Last successful authentication, or null if the partner has never pulled.
    #[serde(rename = "last_used_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "revoked_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "username")]
    pub username: String,
}

impl CredentialSummary {
    pub fn new(branch_id: uuid::Uuid, branch_name: String, created_at: chrono::DateTime<chrono::FixedOffset>, id: uuid::Uuid, name: String, username: String) -> CredentialSummary {
        CredentialSummary {
            branch_id,
            branch_name,
            created_at,
            id,
            last_used_at: None,
            name,
            revoked_at: None,
            username,
        }
    }
}

