/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveryMenuCategory {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "image_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_translations")]
    pub name_translations: serde_json::Value,
}

impl DeliveryMenuCategory {
    pub fn new(id: uuid::Uuid, name: String, name_translations: serde_json::Value) -> DeliveryMenuCategory {
        DeliveryMenuCategory {
            id,
            image_url: None,
            name,
            name_translations,
        }
    }
}

