/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeliveryTracking : Customer-safe tracking view of a delivery order, keyed by its opaque UUID (same capability-URL trust model as the device-token flow). No phone number is exposed; the destination fields are the customer's own inputs. Powers the public `/track/{id}` page (polled, since the public surface has no SSE).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveryTracking {
    #[serde(rename = "address_line", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address_line: Option<Option<String>>,
    #[serde(rename = "branch_name")]
    pub branch_name: String,
    #[serde(rename = "cancel_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cancel_reason: Option<Option<String>>,
    #[serde(rename = "cancelled_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cancelled_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "confirmed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub confirmed_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "customer_name")]
    pub customer_name: String,
    #[serde(rename = "delivered_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "delivery_fee")]
    pub delivery_fee: i32,
    #[serde(rename = "delivery_ref", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delivery_ref: Option<Option<String>>,
    #[serde(rename = "discount_amount")]
    pub discount_amount: i32,
    /// Branch base prep time + the teller's per-order addition (minutes).
    #[serde(rename = "estimated_prep_minutes")]
    pub estimated_prep_minutes: i32,
    #[serde(rename = "floor", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub floor: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "out_for_delivery_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub out_for_delivery_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "payment_method_hint", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_method_hint: Option<Option<String>>,
    #[serde(rename = "place_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub place_name: Option<Option<String>>,
    #[serde(rename = "preparing_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preparing_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "ready_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ready_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "rejected_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rejected_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "subtotal")]
    pub subtotal: i32,
    #[serde(rename = "total")]
    pub total: i32,
    #[serde(rename = "unit_number", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unit_number: Option<Option<String>>,
}

impl DeliveryTracking {
    /// Customer-safe tracking view of a delivery order, keyed by its opaque UUID (same capability-URL trust model as the device-token flow). No phone number is exposed; the destination fields are the customer's own inputs. Powers the public `/track/{id}` page (polled, since the public surface has no SSE).
    pub fn new(branch_name: String, channel: String, created_at: chrono::DateTime<chrono::FixedOffset>, customer_name: String, delivery_fee: i32, discount_amount: i32, estimated_prep_minutes: i32, id: uuid::Uuid, org_id: uuid::Uuid, status: String, subtotal: i32, total: i32) -> DeliveryTracking {
        DeliveryTracking {
            address_line: None,
            branch_name,
            cancel_reason: None,
            cancelled_at: None,
            channel,
            confirmed_at: None,
            created_at,
            customer_name,
            delivered_at: None,
            delivery_fee,
            delivery_ref: None,
            discount_amount,
            estimated_prep_minutes,
            floor: None,
            id,
            org_id,
            out_for_delivery_at: None,
            payment_method_hint: None,
            place_name: None,
            preparing_at: None,
            ready_at: None,
            rejected_at: None,
            status,
            subtotal,
            total,
            unit_number: None,
        }
    }
}

