/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveryMenu {
    /// Org-wide addon catalog (global, POS model): channel-effective, grouped by `type`, applicable to every item. Channel-unavailable options are excluded.
    #[serde(rename = "addons")]
    pub addons: Vec<models::DeliveryAddonOption>,
    #[serde(rename = "categories")]
    pub categories: Vec<models::DeliveryMenuCategory>,
    /// The deals on offer on this channel now (§11.2): checkout applies the best ones automatically (`POST …/cart-quote` shows them). Additive.
    #[serde(rename = "deals")]
    pub deals: Vec<models::DealRule>,
    /// The active discount for this channel (customer-facing) or `null`. Applies to the item subtotal only — the delivery fee is always charged in full.
    #[serde(
        rename = "discount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discount: Option<Option<Box<models::DeliveryMenuDiscount>>>,
    #[serde(rename = "items")]
    pub items: Vec<models::DeliveryMenuItem>,
}

impl DeliveryMenu {
    pub fn new(
        addons: Vec<models::DeliveryAddonOption>,
        categories: Vec<models::DeliveryMenuCategory>,
        deals: Vec<models::DealRule>,
        items: Vec<models::DeliveryMenuItem>,
    ) -> DeliveryMenu {
        DeliveryMenu {
            addons,
            categories,
            deals,
            discount: None,
            items,
        }
    }
}
