/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceKind : OpenAPI-only vocabulary for `devices.kind` (CHECK `kind IN ('pos','kds','waiter')`). The struct fields stay `String`, so the wire strings are unchanged.
/// OpenAPI-only vocabulary for `devices.kind` (CHECK `kind IN ('pos','kds','waiter')`). The struct fields stay `String`, so the wire strings are unchanged.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceKind {
    #[serde(rename = "pos")]
    Pos,
    #[serde(rename = "kds")]
    Kds,
    #[serde(rename = "waiter")]
    Waiter,
}

impl std::fmt::Display for DeviceKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pos => write!(f, "pos"),
            Self::Kds => write!(f, "kds"),
            Self::Waiter => write!(f, "waiter"),
        }
    }
}

impl Default for DeviceKind {
    fn default() -> DeviceKind {
        Self::Pos
    }
}
