/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Device {
    #[serde(
        rename = "app_version",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub app_version: Option<Option<String>>,
    #[serde(
        rename = "branch_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub branch_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "code")]
    pub code: String,
    /// Another live device at the same branch uses the same code.
    #[serde(rename = "code_conflict")]
    pub code_conflict: bool,
    #[serde(rename = "first_seen_at")]
    pub first_seen_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(
        rename = "label",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub label: Option<Option<String>>,
    #[serde(rename = "last_seen_at")]
    pub last_seen_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(
        rename = "platform",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub platform: Option<Option<String>>,
    #[serde(
        rename = "retired_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub retired_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl Device {
    pub fn new(
        code: String,
        code_conflict: bool,
        first_seen_at: chrono::DateTime<chrono::FixedOffset>,
        id: uuid::Uuid,
        kind: String,
        last_seen_at: chrono::DateTime<chrono::FixedOffset>,
        org_id: uuid::Uuid,
    ) -> Device {
        Device {
            app_version: None,
            branch_id: None,
            code,
            code_conflict,
            first_seen_at,
            id,
            kind,
            label: None,
            last_seen_at,
            org_id,
            platform: None,
            retired_at: None,
        }
    }
}
