/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisciplineRow {
    #[serde(rename = "absent_days")]
    pub absent_days: i64,
    /// `None` for a person with no department set — grouped as \"Unassigned\".
    #[serde(
        rename = "department_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub department_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "department_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub department_name: Option<Option<String>>,
    #[serde(rename = "employee_id")]
    pub employee_id: uuid::Uuid,
    #[serde(rename = "employee_name")]
    pub employee_name: String,
    #[serde(rename = "late_days")]
    pub late_days: i64,
    #[serde(rename = "present_days")]
    pub present_days: i64,
    /// 1 = best in this department: fewest absences, then fewest lates, then least total late time. Ties share a rank (SQL `RANK()`), so a department where everyone has a clean record is all `1`s.
    #[serde(rename = "rank_in_department")]
    pub rank_in_department: i64,
    #[serde(rename = "total_late_minutes")]
    pub total_late_minutes: i64,
}

impl DisciplineRow {
    pub fn new(
        absent_days: i64,
        employee_id: uuid::Uuid,
        employee_name: String,
        late_days: i64,
        present_days: i64,
        rank_in_department: i64,
        total_late_minutes: i64,
    ) -> DisciplineRow {
        DisciplineRow {
            absent_days,
            department_id: None,
            department_name: None,
            employee_id,
            employee_name,
            late_days,
            present_days,
            rank_in_department,
            total_late_minutes,
        }
    }
}
