/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Discount {
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "dtype")]
    pub dtype: String,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_translations")]
    pub name_translations: serde_json::Value,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    /// LEGACY SPELLING — an integer, 0-100 for a percentage, minor units for `fixed`. What every shipped client was generated against; see `discounts::wire`. Read [`Discount::value_rate`] for the real stored number.
    #[serde(rename = "value")]
    pub value: i64,
    /// The stored value: a FRACTION for `percentage` (0.14 = 14%, like every other rate in this schema), or minor units for `fixed`. The same column as [`Discount::value`], spelled the way the engine holds it.
    #[serde(rename = "value_rate", skip_serializing_if = "Option::is_none")]
    pub value_rate: Option<f64>,
}

impl Discount {
    pub fn new(
        created_at: chrono::DateTime<chrono::FixedOffset>,
        dtype: String,
        id: uuid::Uuid,
        is_active: bool,
        name: String,
        name_translations: serde_json::Value,
        org_id: uuid::Uuid,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        value: i64,
    ) -> Discount {
        Discount {
            created_at,
            dtype,
            id,
            is_active,
            name,
            name_translations,
            org_id,
            updated_at,
            value,
            value_rate: None,
        }
    }
}
