/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EarningItemList : The list in force at a scope, and whether it came from the org.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EarningItemList {
    #[serde(
        rename = "branch_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub branch_id: Option<Option<uuid::Uuid>>,
    /// True when these rows are the org's rather than this branch's own.
    #[serde(rename = "inherited")]
    pub inherited: bool,
    /// Empty means EVERY item collects — not that nothing does.
    #[serde(rename = "items")]
    pub items: Vec<models::EarningItem>,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
}

impl EarningItemList {
    /// The list in force at a scope, and whether it came from the org.
    pub fn new(
        inherited: bool,
        items: Vec<models::EarningItem>,
        org_id: uuid::Uuid,
    ) -> EarningItemList {
        EarningItemList {
            branch_id: None,
            inherited,
            items,
            org_id,
        }
    }
}
