/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Employee {
    /// `None` when the caller lacks `payroll:read` — see the module docs.
    #[serde(rename = "base_salary_piastres", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub base_salary_piastres: Option<Option<i64>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "department_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub department_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "department_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub department_name: Option<Option<String>>,
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "emergency_contact_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub emergency_contact_name: Option<Option<String>>,
    #[serde(rename = "emergency_contact_phone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub emergency_contact_phone: Option<Option<String>>,
    #[serde(rename = "employee_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub employee_code: Option<Option<String>>,
    #[serde(rename = "employment_status")]
    pub employment_status: String,
    #[serde(rename = "hire_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub hire_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "job_title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub job_title: Option<Option<String>>,
    /// From `users` — the employee's name IS their user name; there is no second copy to drift.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "national_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub national_id: Option<Option<String>>,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "phone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phone: Option<Option<String>>,
    #[serde(rename = "photo_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub photo_url: Option<Option<String>>,
    /// The POS role. Orthogonal to employment: a cleaner is a `teller`-role user with the POS permissions revoked.
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "termination_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub termination_date: Option<Option<chrono::NaiveDate>>,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl Employee {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, employment_status: String, is_active: bool, name: String, org_id: uuid::Uuid, role: String, updated_at: chrono::DateTime<chrono::FixedOffset>, user_id: uuid::Uuid) -> Employee {
        Employee {
            base_salary_piastres: None,
            created_at,
            department_id: None,
            department_name: None,
            email: None,
            emergency_contact_name: None,
            emergency_contact_phone: None,
            employee_code: None,
            employment_status,
            hire_date: None,
            is_active,
            job_title: None,
            name,
            national_id: None,
            notes: None,
            org_id,
            phone: None,
            photo_url: None,
            role,
            termination_date: None,
            updated_at,
            user_id,
        }
    }
}

