/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FairnessRow {
    /// `m` · `f` · null (not set)
    #[serde(
        rename = "gender",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub gender: Option<Option<String>>,
    #[serde(rename = "night_shifts")]
    pub night_shifts: i64,
    #[serde(rename = "people")]
    pub people: i64,
    #[serde(rename = "shifts")]
    pub shifts: i64,
    /// Said they prefer evenings.
    #[serde(rename = "willing")]
    pub willing: i64,
}

impl FairnessRow {
    pub fn new(night_shifts: i64, people: i64, shifts: i64, willing: i64) -> FairnessRow {
        FairnessRow {
            gender: None,
            night_shifts,
            people,
            shifts,
            willing,
        }
    }
}
