/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FinalizeInput {
    /// The actual method the customer paid (overrides the hint). Must be an org method.
    #[serde(rename = "payment_method")]
    pub payment_method: String,
    #[serde(rename = "shift_id")]
    pub shift_id: uuid::Uuid,
}

impl FinalizeInput {
    pub fn new(payment_method: String, shift_id: uuid::Uuid) -> FinalizeInput {
        FinalizeInput {
            payment_method,
            shift_id,
        }
    }
}

