/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FinalizeResponse {
    #[serde(rename = "delivery_order")]
    pub delivery_order: Box<models::DeliveryOrder>,
    #[serde(rename = "order_id")]
    pub order_id: uuid::Uuid,
    #[serde(rename = "order_ref", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub order_ref: Option<Option<String>>,
    #[serde(rename = "warnings")]
    pub warnings: Vec<String>,
}

impl FinalizeResponse {
    pub fn new(delivery_order: models::DeliveryOrder, order_id: uuid::Uuid, warnings: Vec<String>) -> FinalizeResponse {
        FinalizeResponse {
            delivery_order: Box::new(delivery_order),
            order_id,
            order_ref: None,
            warnings,
        }
    }
}

