/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoodsReceipt {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// true ⟹ a return to supplier (negative stock effect).
    #[serde(rename = "is_return")]
    pub is_return: bool,
    #[serde(rename = "lines")]
    pub lines: Vec<models::GoodsReceiptLine>,
    #[serde(rename = "note", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub note: Option<Option<String>>,
    #[serde(rename = "purchase_order_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub purchase_order_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "received_at")]
    pub received_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "received_by")]
    pub received_by: uuid::Uuid,
    #[serde(rename = "received_by_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub received_by_name: Option<Option<String>>,
    #[serde(rename = "reference", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reference: Option<Option<String>>,
    #[serde(rename = "supplier_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub supplier_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "supplier_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub supplier_name: Option<Option<String>>,
}

impl GoodsReceipt {
    pub fn new(branch_id: uuid::Uuid, id: uuid::Uuid, is_return: bool, lines: Vec<models::GoodsReceiptLine>, received_at: chrono::DateTime<chrono::FixedOffset>, received_by: uuid::Uuid) -> GoodsReceipt {
        GoodsReceipt {
            branch_id,
            id,
            is_return,
            lines,
            note: None,
            purchase_order_id: None,
            received_at,
            received_by,
            received_by_name: None,
            reference: None,
            supplier_id: None,
            supplier_name: None,
        }
    }
}

