/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngredientCategory {
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// Live (non-deleted) ingredients in this category.
    #[serde(rename = "ingredient_count")]
    pub ingredient_count: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    /// Stable machine key (`general`, `milk`, `coffee_bean`, …). `milk` and `coffee_bean` carry swap semantics in the menu; the slug never changes.
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "sort_order")]
    pub sort_order: i32,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl IngredientCategory {
    pub fn new(
        created_at: chrono::DateTime<chrono::FixedOffset>,
        id: uuid::Uuid,
        ingredient_count: i64,
        name: String,
        org_id: uuid::Uuid,
        slug: String,
        sort_order: i32,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> IngredientCategory {
        IngredientCategory {
            created_at,
            id,
            ingredient_count,
            name,
            org_id,
            slug,
            sort_order,
            updated_at,
        }
    }
}
