/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemRouteInput {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "menu_item_id")]
    pub menu_item_id: uuid::Uuid,
    #[serde(rename = "station_id")]
    pub station_id: uuid::Uuid,
}

impl ItemRouteInput {
    pub fn new(branch_id: uuid::Uuid, menu_item_id: uuid::Uuid, station_id: uuid::Uuid) -> ItemRouteInput {
        ItemRouteInput {
            branch_id,
            menu_item_id,
            station_id,
        }
    }
}

