/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LateDeductionKind : What a tier costs the employee.
/// What a tier costs the employee.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LateDeductionKind {
    #[serde(rename = "minutes")]
    Minutes,
    #[serde(rename = "piastres")]
    Piastres,
    #[serde(rename = "day_fraction")]
    DayFraction,
}

impl std::fmt::Display for LateDeductionKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Minutes => write!(f, "minutes"),
            Self::Piastres => write!(f, "piastres"),
            Self::DayFraction => write!(f, "day_fraction"),
        }
    }
}

impl Default for LateDeductionKind {
    fn default() -> LateDeductionKind {
        Self::Minutes
    }
}
