/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LedgerTotals {
    /// Σ(target·revenue − margin) over below-target rows — \"margin left on the table\" this period, in piastres.
    #[serde(rename = "below_target_gap")]
    pub below_target_gap: i64,
    /// Cost summed over rows where it is known.
    #[serde(rename = "cost_known")]
    pub cost_known: i64,
    #[serde(rename = "margin_known")]
    pub margin_known: i64,
    #[serde(
        rename = "margin_pct",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub margin_pct: Option<Option<f64>>,
    #[serde(rename = "prev_margin_known")]
    pub prev_margin_known: i64,
    #[serde(rename = "prev_revenue")]
    pub prev_revenue: i64,
    #[serde(rename = "revenue")]
    pub revenue: i64,
    /// Revenue sitting on rows whose cost is unknown (visibly reconciles).
    #[serde(rename = "revenue_cost_unknown")]
    pub revenue_cost_unknown: i64,
}

impl LedgerTotals {
    pub fn new(
        below_target_gap: i64,
        cost_known: i64,
        margin_known: i64,
        prev_margin_known: i64,
        prev_revenue: i64,
        revenue: i64,
        revenue_cost_unknown: i64,
    ) -> LedgerTotals {
        LedgerTotals {
            below_target_gap,
            cost_known,
            margin_known,
            margin_pct: None,
            prev_margin_known,
            prev_revenue,
            revenue,
            revenue_cost_unknown,
        }
    }
}
