/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinksPageSettings : The editor's view: what is saved, plus what it is built from.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinksPageSettings {
    /// Every active branch, with its settings.
    #[serde(rename = "branches")]
    pub branches: Vec<models::LinksPageBranch>,
    /// The shop's card image, which the page uses as its cover.
    #[serde(
        rename = "card_image_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub card_image_url: Option<Option<String>>,
    /// Whether the shop wears its own colours on the page.
    #[serde(rename = "custom_branding")]
    pub custom_branding: bool,
    #[serde(rename = "items")]
    pub items: Vec<models::LinksPageItem>,
    #[serde(
        rename = "loyalty_mode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub loyalty_mode: Option<Option<String>>,
    #[serde(rename = "modules")]
    pub modules: Vec<models::LinksModuleStatus>,
    /// Where the page is: the root of the shop's own host, for a shop on the branding tier with a slug. `None` otherwise — there is no generic links host.
    #[serde(
        rename = "public_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub public_url: Option<Option<String>>,
    #[serde(rename = "show_branches")]
    pub show_branches: bool,
    #[serde(rename = "show_cover")]
    pub show_cover: bool,
    /// `organizations.social_links`, as stored.
    #[serde(rename = "social_links")]
    pub social_links: serde_json::Value,
    #[serde(
        rename = "tagline_ar",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tagline_ar: Option<Option<String>>,
    #[serde(
        rename = "tagline_en",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tagline_en: Option<Option<String>>,
}

impl LinksPageSettings {
    /// The editor's view: what is saved, plus what it is built from.
    pub fn new(
        branches: Vec<models::LinksPageBranch>,
        custom_branding: bool,
        items: Vec<models::LinksPageItem>,
        modules: Vec<models::LinksModuleStatus>,
        show_branches: bool,
        show_cover: bool,
        social_links: serde_json::Value,
    ) -> LinksPageSettings {
        LinksPageSettings {
            branches,
            card_image_url: None,
            custom_branding,
            items,
            loyalty_mode: None,
            modules,
            public_url: None,
            show_branches,
            show_cover,
            social_links,
            tagline_ar: None,
            tagline_en: None,
        }
    }
}
