/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginResponse {
    #[serde(rename = "currency_code")]
    pub currency_code: String,
    /// The person's open till at the branch they signed into (any device), so the device can resume it or show where it is open.
    #[serde(
        rename = "open_till",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub open_till: Option<Option<Box<models::TillBrief>>>,
    /// Every dine-in sale belongs to a table.  The till needs this, not just the server: the rule changes what the POS puts in front of a teller — the floor becomes the home screen and a sale starts by picking a table — and a refusal AFTER the items are rung up is far too late to be useful.
    #[serde(
        rename = "require_table_for_orders",
        skip_serializing_if = "Option::is_none"
    )]
    pub require_table_for_orders: Option<bool>,
    /// The full policy, including tax-inclusive pricing and service charge. Prefer this over the flat `tax_rate` above.
    #[serde(rename = "tax_policy")]
    pub tax_policy: Box<models::TaxPolicyPublic>,
    /// Org tax rate as a decimal (e.g. 0.14 = 14% VAT); 0.0 when no org. Mirrors /auth/me so the POS has it immediately after login.
    #[serde(rename = "tax_rate")]
    pub tax_rate: f64,
    /// JWT to send as `Authorization: Bearer <token>` on subsequent requests.
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "user")]
    pub user: Box<models::UserPublic>,
}

impl LoginResponse {
    pub fn new(
        currency_code: String,
        tax_policy: models::TaxPolicyPublic,
        tax_rate: f64,
        token: String,
        user: models::UserPublic,
    ) -> LoginResponse {
        LoginResponse {
            currency_code,
            open_till: None,
            require_table_for_orders: None,
            tax_policy: Box::new(tax_policy),
            tax_rate,
            token,
            user: Box::new(user),
        }
    }
}
