/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoyaltySettings {
    /// When a void or refund claws back points the member has already spent, may the balance go below zero?  Off (the default) clamps at zero: the shop eats the reward that was already handed over, and the earn stays visibly part-reversed on the ledger against an order that says `voided`, so a report can list who benefited and by how much. On, the balance goes negative and the next visits earn into the hole — the books balance, and the customer sees a minus on their card for what was nearly always the shop's own mistake.  Clawbacks ONLY. A redemption or a manual deduction can never overdraw whatever this says: you cannot spend what you do not have; you can only owe because a sale you were paid for was undone. Enforced in the database (`loyalty_apply_txn`), not here.
    #[serde(
        rename = "allow_negative_balance",
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_negative_balance: Option<bool>,
    /// The ceiling, when `balance_cap_enabled`. `None` = derive it.  A `None` here is NOT \"no cap\" — that is what the switch is for. It means the most expensive reward on offer at this scope, read from the catalogue at award time. Once a customer can claim anything in the programme, collecting more buys them nothing and leaves the shop carrying a liability it never chose; and because it is derived, adding a dearer reward raises the ceiling without anyone retyping it.  Earning at the cap is DROPPED, not refused: the sale is not the customer's doing and must not fail because their card is full.
    #[serde(
        rename = "balance_cap",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub balance_cap: Option<Option<i32>>,
    /// Whether a ceiling applies to what a member may hold at all.  Separate from the figure below, because \"no number\" has to be able to mean something. Off, a card collects without end.
    #[serde(
        rename = "balance_cap_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub balance_cap_enabled: Option<bool>,
    /// Ask for a birthday at signup, and greet them on the day.  Off means the form does not ASK — not that it asks and ignores. A date of birth is the most sensitive thing this feature collects, and a shop that does not run birthday rewards has no business holding one.
    #[serde(rename = "birthday_enabled", skip_serializing_if = "Option::is_none")]
    pub birthday_enabled: Option<bool>,
    /// Overrides the built-in greeting. `{name}` is substituted; nothing else is.
    #[serde(
        rename = "birthday_message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub birthday_message: Option<Option<String>>,
    #[serde(
        rename = "birthday_message_ar",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub birthday_message_ar: Option<Option<String>>,
    /// Points or stamps given on the day. `None` is a greeting and nothing else, which is deliberately the default: plenty of shops want to say happy birthday without giving away a drink.
    #[serde(
        rename = "birthday_reward_amount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub birthday_reward_amount: Option<Option<i32>>,
    /// `null` = the org-wide default. A branch id = that branch's override.
    #[serde(
        rename = "branch_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub branch_id: Option<Option<uuid::Uuid>>,
    /// The cost offered by default when an admin adds a reward, in whatever this scope collects. Each reward may override it, so one catalogue holds \"espresso, 5 visits\" beside \"cake, 10 visits\". Also the pass's fallback target when no rewards have been curated yet.
    #[serde(rename = "default_reward_cost")]
    pub default_reward_cost: i32,
    /// Add tax to the basis. Tips never earn and have no toggle.
    #[serde(rename = "earn_include_tax")]
    pub earn_include_tax: bool,
    /// Earn on what was actually paid rather than the pre-discount subtotal.
    #[serde(rename = "earn_on_discounted")]
    pub earn_on_discounted: bool,
    /// One point per this many piastres. 1000 = a point per 10 EGP. The dashboard shows and accepts EGP; the wire is always piastres.
    #[serde(rename = "earn_piastres_per_point")]
    pub earn_piastres_per_point: i32,
    /// The ceiling actually in force, once derived. **Read-only.**  `balance_cap` is what the shop TYPED, which is usually nothing; this is what that resolves to against the current catalogue. The dashboard shows it so \"leave it empty\" is a visible number rather than a promise, and so the figure on screen is the one the award path will use rather than the dashboard's own guess at it.  `null` when no ceiling applies.
    #[serde(
        rename = "effective_balance_cap",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub effective_balance_cap: Option<Option<i32>>,
    /// The program switch for this scope.
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// How many active branches have coordinates set. **Read-only.**  The one thing that decides whether a saved card can notify a customer when they are at the shop. Both wallets geofence from the branch coordinates on the pass, so a programme whose branches have none gets no location prompt on the phone and no nearby notification — and nothing anywhere said so, which reads as the wallet being broken rather than as a field nobody filled in.  Read-only in effect: this type doubles as the PUT body, and the write path binds its columns explicitly, so a value sent here is parsed and then ignored. It is a fact about `branches`, answered on this page because this is where someone wonders why the card is silent.
    #[serde(rename = "geofenced_branches", skip_serializing_if = "Option::is_none")]
    pub geofenced_branches: Option<i64>,
    /// How many rewards one order may claim. `None` = unlimited.  `Some(1)` is the setting most shops mean when they ask for this: a member with thirty stamps and a five-stamp reward can otherwise take six free items in one visit, which is the same giveaway the shop believed it was spreading over six.
    #[serde(
        rename = "max_rewards_per_order",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_rewards_per_order: Option<Option<i32>>,
    /// What this scope collects: `\"points\"` (from money spent) or `\"visits\"` (one stamp per sale). One or the other — never both.
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "program_name")]
    pub program_name: String,
    #[serde(
        rename = "program_name_ar",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub program_name_ar: Option<Option<String>>,
    /// Verify the signup phone by WhatsApp code, like bookings and ordering.
    #[serde(rename = "require_otp")]
    pub require_otp: bool,
    /// Any menu item may be taken as a reward, at `default_reward_cost`.  Off by default. A curated catalogue is the safer shape — it offers an espresso for five stamps without also offering the steak — and this is for the shops whose programme genuinely is \"collect five, get anything\", which a catalogue can only express by listing the entire menu and keeping that list in step with it forever.  The two are alternatives, not layers: with this on, the catalogue's per-item prices no longer apply, because an item's cost can no longer depend on which item it is.  Defaulted on the way in, because this type is the REQUEST body as well as the response: every till and dashboard already in the field sends a settings object without this key, and rejecting those would switch the programme off for everyone who had not updated yet.
    #[serde(rename = "reward_any_item", skip_serializing_if = "Option::is_none")]
    pub reward_any_item: Option<bool>,
    #[serde(
        rename = "terms",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub terms: Option<Option<String>>,
    #[serde(
        rename = "terms_ar",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub terms_ar: Option<Option<String>>,
    /// Nudge a member who has not been in for a while. Off by default, like everything here that speaks to a customer unprompted.  The timing is not a per-shop setting: how long \"a while\" is, whether it repeats, and how stale is too stale are one operational judgement across the estate, and they live in the environment (`LOYALTY_WINBACK_*`) rather than in a form where a shop could set it to a day and burn its own list down.
    #[serde(rename = "winback_enabled", skip_serializing_if = "Option::is_none")]
    pub winback_enabled: Option<bool>,
    /// ONE override, in whichever language the shop writes it, replacing the built-in English and Arabic both. `{name}` is substituted; nothing else.  Unset is the better default: the built-ins are written in each language rather than translated into one, so a customer reads a sentence that was composed for them.
    #[serde(
        rename = "winback_message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub winback_message: Option<Option<String>>,
    /// Points or stamps to arrive with the nudge. `None` is words only.
    #[serde(
        rename = "winback_reward_amount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub winback_reward_amount: Option<Option<i32>>,
}

impl LoyaltySettings {
    pub fn new(
        default_reward_cost: i32,
        earn_include_tax: bool,
        earn_on_discounted: bool,
        earn_piastres_per_point: i32,
        enabled: bool,
        mode: String,
        org_id: uuid::Uuid,
        program_name: String,
        require_otp: bool,
    ) -> LoyaltySettings {
        LoyaltySettings {
            allow_negative_balance: None,
            balance_cap: None,
            balance_cap_enabled: None,
            birthday_enabled: None,
            birthday_message: None,
            birthday_message_ar: None,
            birthday_reward_amount: None,
            branch_id: None,
            default_reward_cost,
            earn_include_tax,
            earn_on_discounted,
            earn_piastres_per_point,
            effective_balance_cap: None,
            enabled,
            geofenced_branches: None,
            max_rewards_per_order: None,
            mode,
            org_id,
            program_name,
            program_name_ar: None,
            require_otp,
            reward_any_item: None,
            terms: None,
            terms_ar: None,
            winback_enabled: None,
            winback_message: None,
            winback_reward_amount: None,
        }
    }
}
