/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MemberView : A member as the teller, the admin and the pass all see them.  Both balances travel, because an org may switch mode (or run points at one branch and stamps at another) and what a customer earned under the old rules is still theirs. `mode` says which one is LIVE where the question was asked, and `balance` is that one — so a caller never has to pick.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemberView {
    /// The live balance, in `mode`'s currency.
    #[serde(rename = "balance")]
    pub balance: i32,
    /// The balance affords at least one reward on offer here.
    #[serde(rename = "can_redeem")]
    pub can_redeem: bool,
    #[serde(rename = "enrolled_at")]
    pub enrolled_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "lifetime_points")]
    pub lifetime_points: i32,
    #[serde(rename = "lifetime_visits")]
    pub lifetime_visits: i32,
    #[serde(rename = "locale")]
    pub locale: String,
    /// `\"points\"` or `\"visits\"` — what the branch that asked collects.
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "name")]
    pub name: String,
    /// The cheapest reward on offer here, in `mode`'s currency — what the progress line counts towards. Falls back to the scope's default cost when no rewards have been curated.
    #[serde(rename = "next_reward_cost")]
    pub next_reward_cost: i32,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "phone")]
    pub phone: String,
    #[serde(rename = "points_balance")]
    pub points_balance: i32,
    /// `next_reward_cost - balance`, floored at zero.
    #[serde(rename = "points_to_next_reward")]
    pub points_to_next_reward: i32,
    #[serde(rename = "visits_balance")]
    pub visits_balance: i32,
}

impl MemberView {
    /// A member as the teller, the admin and the pass all see them.  Both balances travel, because an org may switch mode (or run points at one branch and stamps at another) and what a customer earned under the old rules is still theirs. `mode` says which one is LIVE where the question was asked, and `balance` is that one — so a caller never has to pick.
    pub fn new(balance: i32, can_redeem: bool, enrolled_at: chrono::DateTime<chrono::FixedOffset>, id: uuid::Uuid, lifetime_points: i32, lifetime_visits: i32, locale: String, mode: String, name: String, next_reward_cost: i32, org_id: uuid::Uuid, phone: String, points_balance: i32, points_to_next_reward: i32, visits_balance: i32) -> MemberView {
        MemberView {
            balance,
            can_redeem,
            enrolled_at,
            id,
            lifetime_points,
            lifetime_visits,
            locale,
            mode,
            name,
            next_reward_cost,
            org_id,
            phone,
            points_balance,
            points_to_next_reward,
            visits_balance,
        }
    }
}

