/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MenuEngineeringReport {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    /// Cost basis the report was computed with: \"snapshot\" | \"current\".
    #[serde(rename = "cost_basis")]
    pub cost_basis: String,
    /// Realized revenue (piastres) carried by the excluded SKUs — explains why `total_sales` differs between cost bases: each basis excludes a different set of un-costable rows.
    #[serde(rename = "excluded_sales")]
    pub excluded_sales: i64,
    #[serde(rename = "from", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub from: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "rows")]
    pub rows: Vec<models::MenuEngineeringRow>,
    /// SKUs sold in the window but EXCLUDED from this report because their cost was unresolvable under the chosen basis.
    #[serde(rename = "rows_cost_missing")]
    pub rows_cost_missing: i64,
    #[serde(rename = "to", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub to: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "total_cost")]
    pub total_cost: i64,
    #[serde(rename = "total_profit")]
    pub total_profit: i64,
    /// Totals over the returned rows.
    #[serde(rename = "total_sales")]
    pub total_sales: i64,
}

impl MenuEngineeringReport {
    pub fn new(branch_id: uuid::Uuid, cost_basis: String, excluded_sales: i64, rows: Vec<models::MenuEngineeringRow>, rows_cost_missing: i64, total_cost: i64, total_profit: i64, total_sales: i64) -> MenuEngineeringReport {
        MenuEngineeringReport {
            branch_id,
            cost_basis,
            excluded_sales,
            from: None,
            rows,
            rows_cost_missing,
            to: None,
            total_cost,
            total_profit,
            total_sales,
        }
    }
}

