/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModifierOptionOut : A modifier option inside an attached group.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifierOptionOut {
    #[serde(rename = "cost_incomplete")]
    pub cost_incomplete: bool,
    /// Option recipe cost in piastres (swap markers cost 0). `null` = unknown.
    #[serde(rename = "cost_piastres", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cost_piastres: Option<Option<i64>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// `false` = the group offers this option but it is not enabled on this item (item's `included_option_ids` allowlist excludes it).
    #[serde(rename = "included")]
    pub included: bool,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "is_default")]
    pub is_default: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "price")]
    pub price: i32,
    #[serde(rename = "recipe")]
    pub recipe: Vec<models::RecipeLineOut>,
    #[serde(rename = "replaces_ingredient_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub replaces_ingredient_id: Option<Option<uuid::Uuid>>,
}

impl ModifierOptionOut {
    /// A modifier option inside an attached group.
    pub fn new(cost_incomplete: bool, id: uuid::Uuid, included: bool, is_active: bool, is_default: bool, name: String, price: i32, recipe: Vec<models::RecipeLineOut>) -> ModifierOptionOut {
        ModifierOptionOut {
            cost_incomplete,
            cost_piastres: None,
            id,
            included,
            is_active,
            is_default,
            name,
            price,
            recipe,
            replaces_ingredient_id: None,
        }
    }
}

