/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MoveView {
    #[serde(rename = "from")]
    pub from: Box<models::DayView>,
    #[serde(rename = "to")]
    pub to: Box<models::DayView>,
}

impl MoveView {
    pub fn new(from: models::DayView, to: models::DayView) -> MoveView {
        MoveView {
            from: Box::new(from),
            to: Box::new(to),
        }
    }
}
