/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MyClaim : One of my claims on an open shift, and how it ended (SC-9, S-162): a request like any other, so it stays in my Requests once decided.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MyClaim {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "claimed_at")]
    pub claimed_at: chrono::DateTime<chrono::FixedOffset>,
    /// When it was decided or withdrawn; null while pending, and on a claim decided before the server kept this history.
    #[serde(
        rename = "decided_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub decided_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "on_date")]
    pub on_date: chrono::NaiveDate,
    #[serde(rename = "open_shift_id")]
    pub open_shift_id: uuid::Uuid,
    #[serde(rename = "shift_name")]
    pub shift_name: String,
    /// `pending` · `approved` · `declined` · `withdrawn`. A shift the manager took back while the claim waited is `declined`.
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "work_shift_id")]
    pub work_shift_id: uuid::Uuid,
}

impl MyClaim {
    /// One of my claims on an open shift, and how it ended (SC-9, S-162): a request like any other, so it stays in my Requests once decided.
    pub fn new(
        branch_id: uuid::Uuid,
        claimed_at: chrono::DateTime<chrono::FixedOffset>,
        id: uuid::Uuid,
        on_date: chrono::NaiveDate,
        open_shift_id: uuid::Uuid,
        shift_name: String,
        status: String,
        work_shift_id: uuid::Uuid,
    ) -> MyClaim {
        MyClaim {
            branch_id,
            claimed_at,
            decided_at: None,
            id,
            on_date,
            open_shift_id,
            shift_name,
            status,
            work_shift_id,
        }
    }
}
