/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenShift {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    /// The employee who claimed it.
    #[serde(
        rename = "claimed_by",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub claimed_by: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "claimed_by_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub claimed_by_name: Option<Option<String>>,
    #[serde(
        rename = "end_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub end_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "on_date")]
    pub on_date: chrono::NaiveDate,
    #[serde(rename = "shift_name")]
    pub shift_name: String,
    #[serde(
        rename = "start_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub start_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// `open` · `claimed` · `filled` · `cancelled`
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "work_shift_id")]
    pub work_shift_id: uuid::Uuid,
}

impl OpenShift {
    pub fn new(
        branch_id: uuid::Uuid,
        id: uuid::Uuid,
        on_date: chrono::NaiveDate,
        shift_name: String,
        status: String,
        work_shift_id: uuid::Uuid,
    ) -> OpenShift {
        OpenShift {
            branch_id,
            claimed_by: None,
            claimed_by_name: None,
            end_at: None,
            id,
            on_date,
            shift_name,
            start_at: None,
            status,
            work_shift_id,
        }
    }
}
