/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptionRecipeLineInput : One recipe line as submitted to the option-recipe replace endpoint. `quantity` may be 0 (a swap marker). Server normalizes to the ingredient base unit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OptionRecipeLineInput {
    #[serde(rename = "ingredient_id")]
    pub ingredient_id: uuid::Uuid,
    #[serde(rename = "quantity")]
    pub quantity: f64,
    #[serde(rename = "unit")]
    pub unit: String,
}

impl OptionRecipeLineInput {
    /// One recipe line as submitted to the option-recipe replace endpoint. `quantity` may be 0 (a swap marker). Server normalizes to the ingredient base unit.
    pub fn new(ingredient_id: uuid::Uuid, quantity: f64, unit: String) -> OptionRecipeLineInput {
        OptionRecipeLineInput {
            ingredient_id,
            quantity,
            unit,
        }
    }
}

