/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderItemInput {
    #[serde(rename = "addons", skip_serializing_if = "Option::is_none")]
    pub addons: Option<Vec<models::AddonInput>>,
    /// A line naming a combo item (`kind=combo`) carries its picks here; see COMBOS_CONTRACT.md §3.1. On replay `unit_price` is P as the till charged it and each pick's `share`/`surcharge` are per combo unit. Additive.
    #[serde(
        rename = "combo",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub combo: Option<Option<Box<models::ComboInput>>>,
    #[serde(
        rename = "menu_item_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub menu_item_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "notes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notes: Option<Option<String>>,
    #[serde(rename = "optional_field_ids", skip_serializing_if = "Option::is_none")]
    pub optional_field_ids: Option<Vec<uuid::Uuid>>,
    #[serde(rename = "quantity")]
    pub quantity: i32,
    #[serde(
        rename = "size_label",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub size_label: Option<Option<String>>,
    /// Put this line on the branch's STAFF POOL: a normal sale whose base configuration (cheapest size + the default of each required choice) is comped, extras still charged. Needs `orders.staff_drink.record`. The server prices the comp; see `docs/staff-drink-comp-contract.md`. Additive — a client that omits it rings an ordinary paid line. Not carried by a ticket's line.
    #[serde(
        rename = "staff_drink",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub staff_drink: Option<Option<Box<models::StaffDrinkLine>>>,
    /// What the customer was actually charged, in piastres.  Read ONLY when a queued offline sale is replayed — see [`ClientPrices`]. On the live path the server prices the line and this is ignored, so a till cannot charge a price of its own choosing and no manual override exists to let anyone try.
    #[serde(
        rename = "unit_price",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub unit_price: Option<Option<i32>>,
}

impl OrderItemInput {
    pub fn new(quantity: i32) -> OrderItemInput {
        OrderItemInput {
            addons: None,
            combo: None,
            menu_item_id: None,
            notes: None,
            optional_field_ids: None,
            quantity,
            size_label: None,
            staff_drink: None,
            unit_price: None,
        }
    }
}
