/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderSummary {
    #[serde(rename = "completed")]
    pub completed: i64,
    /// Total delivery charges (piastres) across completed orders in scope. Lets the dashboard surface delivery revenue separately from item sales.
    #[serde(rename = "delivery_fees", skip_serializing_if = "Option::is_none")]
    pub delivery_fees: Option<i64>,
    /// Count of completed delivery orders.
    #[serde(rename = "delivery_orders", skip_serializing_if = "Option::is_none")]
    pub delivery_orders: Option<i64>,
    /// Gross revenue (total_amount) of completed delivery orders.
    #[serde(rename = "delivery_revenue", skip_serializing_if = "Option::is_none")]
    pub delivery_revenue: Option<i64>,
    #[serde(rename = "discounts")]
    pub discounts: i64,
    #[serde(rename = "in_mall_fees", skip_serializing_if = "Option::is_none")]
    pub in_mall_fees: Option<i64>,
    /// In-mall channel: order count / gross revenue / delivery fees.
    #[serde(rename = "in_mall_orders", skip_serializing_if = "Option::is_none")]
    pub in_mall_orders: Option<i64>,
    #[serde(rename = "in_mall_revenue", skip_serializing_if = "Option::is_none")]
    pub in_mall_revenue: Option<i64>,
    #[serde(rename = "outside_fees", skip_serializing_if = "Option::is_none")]
    pub outside_fees: Option<i64>,
    /// Outside channel: order count / gross revenue / delivery fees.
    #[serde(rename = "outside_orders", skip_serializing_if = "Option::is_none")]
    pub outside_orders: Option<i64>,
    #[serde(rename = "outside_revenue", skip_serializing_if = "Option::is_none")]
    pub outside_revenue: Option<i64>,
    #[serde(rename = "revenue")]
    pub revenue: i64,
    #[serde(rename = "tips")]
    pub tips: i64,
    #[serde(rename = "voided")]
    pub voided: i64,
}

impl OrderSummary {
    pub fn new(completed: i64, discounts: i64, revenue: i64, tips: i64, voided: i64) -> OrderSummary {
        OrderSummary {
            completed,
            delivery_fees: None,
            delivery_orders: None,
            delivery_revenue: None,
            discounts,
            in_mall_fees: None,
            in_mall_orders: None,
            in_mall_revenue: None,
            outside_fees: None,
            outside_orders: None,
            outside_revenue: None,
            revenue,
            tips,
            voided,
        }
    }
}

