/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderNowContext {
    /// First word of the name on file.
    #[serde(rename = "first_name")]
    pub first_name: String,
    #[serde(
        rename = "full",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub full: Option<Option<Box<models::OrderNowFull>>>,
    /// NAME only on the masked path; the full context carries the id.
    #[serde(
        rename = "last_branch_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_branch_name: Option<Option<String>>,
    #[serde(
        rename = "logo_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub logo_url: Option<Option<String>>,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "org_name")]
    pub org_name: String,
    /// `•••• 4567`.
    #[serde(rename = "phone_hint")]
    pub phone_hint: String,
    /// True → this is the masked context; verify the phone (`/public/otp/request|verify`) and ask again with the device token.
    #[serde(rename = "verify_required")]
    pub verify_required: bool,
}

impl OrderNowContext {
    pub fn new(
        first_name: String,
        org_id: uuid::Uuid,
        org_name: String,
        phone_hint: String,
        verify_required: bool,
    ) -> OrderNowContext {
        OrderNowContext {
            first_name,
            full: None,
            last_branch_name: None,
            logo_url: None,
            org_id,
            org_name,
            phone_hint,
            verify_required,
        }
    }
}
