/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderDealLine {
    #[serde(rename = "discount")]
    pub discount: i32,
    #[serde(rename = "order_item_id")]
    pub order_item_id: uuid::Uuid,
    #[serde(rename = "units")]
    pub units: i32,
}

impl OrderDealLine {
    pub fn new(discount: i32, order_item_id: uuid::Uuid, units: i32) -> OrderDealLine {
        OrderDealLine {
            discount,
            order_item_id,
            units,
        }
    }
}
