/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderNumberRange {
    #[serde(
        rename = "device_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub device_code: Option<Option<String>>,
    #[serde(
        rename = "first",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub first: Option<Option<i32>>,
    #[serde(
        rename = "last",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last: Option<Option<i32>>,
}

impl OrderNumberRange {
    pub fn new() -> OrderNumberRange {
        OrderNumberRange {
            device_code: None,
            first: None,
            last: None,
        }
    }
}
