/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderItem {
    #[serde(rename = "bundle_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bundle_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "bundle_unit_price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bundle_unit_price: Option<Option<i32>>,
    /// True when any cost component could not be resolved.
    #[serde(rename = "cost_missing")]
    pub cost_missing: bool,
    #[serde(rename = "deductions_snapshot", deserialize_with = "Option::deserialize")]
    pub deductions_snapshot: Option<serde_json::Value>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "item_name")]
    pub item_name: String,
    /// Full line COGS in piastres (recipe + addons + optionals + components). `null` ⟺ unknown.
    #[serde(rename = "line_cost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub line_cost: Option<Option<i64>>,
    #[serde(rename = "line_total")]
    pub line_total: i32,
    #[serde(rename = "menu_item_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub menu_item_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "name_translations")]
    pub name_translations: serde_json::Value,
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    #[serde(rename = "order_id")]
    pub order_id: uuid::Uuid,
    #[serde(rename = "quantity")]
    pub quantity: i32,
    #[serde(rename = "size_label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub size_label: Option<Option<String>>,
    /// Recipe-only cost per unit in piastres (incl. swaps). `null` ⟺ unknown or bundle line.
    #[serde(rename = "unit_cost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unit_cost: Option<Option<i64>>,
    #[serde(rename = "unit_price")]
    pub unit_price: i32,
}

impl OrderItem {
    pub fn new(cost_missing: bool, deductions_snapshot: Option<serde_json::Value>, id: uuid::Uuid, item_name: String, line_total: i32, name_translations: serde_json::Value, order_id: uuid::Uuid, quantity: i32, unit_price: i32) -> OrderItem {
        OrderItem {
            bundle_id: None,
            bundle_unit_price: None,
            cost_missing,
            deductions_snapshot,
            id,
            item_name,
            line_cost: None,
            line_total,
            menu_item_id: None,
            name_translations,
            notes: None,
            order_id,
            quantity,
            size_label: None,
            unit_cost: None,
            unit_price,
        }
    }
}

