/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackagingRuleLineOut {
    #[serde(rename = "ingredient_id")]
    pub ingredient_id: uuid::Uuid,
    #[serde(rename = "ingredient_name")]
    pub ingredient_name: String,
    /// Base-unit quantity as a string.
    #[serde(rename = "quantity")]
    pub quantity: String,
    #[serde(rename = "sort")]
    pub sort: i32,
    #[serde(rename = "unit")]
    pub unit: String,
}

impl PackagingRuleLineOut {
    pub fn new(
        ingredient_id: uuid::Uuid,
        ingredient_name: String,
        quantity: String,
        sort: i32,
        unit: String,
    ) -> PackagingRuleLineOut {
        PackagingRuleLineOut {
            ingredient_id,
            ingredient_name,
            quantity,
            sort,
            unit,
        }
    }
}
