/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PassLinks : What signup hands the customer. Either side may be absent: a tenant with only Google credentials configured shows one button, not a broken one.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PassLinks {
    /// False when neither wallet is configured — the site shows the member's QR on the page instead of dead buttons.
    #[serde(rename = "any")]
    pub any: bool,
    /// Downloads the signed `.pkpass`. Site-relative, because the signup page is served from the same origin as the API — so a pass needs a CERTIFICATE, not a configured base URL.
    #[serde(
        rename = "apple_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub apple_url: Option<Option<String>>,
    /// `https://pay.google.com/gp/v/save/<jwt>`.
    #[serde(
        rename = "google_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub google_url: Option<Option<String>>,
}

impl PassLinks {
    /// What signup hands the customer. Either side may be absent: a tenant with only Google credentials configured shows one button, not a broken one.
    pub fn new(any: bool) -> PassLinks {
        PassLinks {
            any,
            apple_url: None,
            google_url: None,
        }
    }
}
