/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchGroupRequest : Every field optional — only present keys are updated. `Option<Option<T>>` (with `deserialize_with`) is avoided; nullable columns that must be clearable (`max_selections`) are handled by a dedicated presence flag pattern below.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchGroupRequest {
    #[serde(rename = "is_required", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_required: Option<Option<bool>>,
    #[serde(rename = "max_selections", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_selections: Option<Option<i32>>,
    #[serde(rename = "min_selections", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub min_selections: Option<Option<i32>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "name_translations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name_translations: Option<Option<serde_json::Value>>,
    #[serde(rename = "selection_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub selection_type: Option<Option<String>>,
    #[serde(rename = "sort", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sort: Option<Option<i32>>,
}

impl PatchGroupRequest {
    /// Every field optional — only present keys are updated. `Option<Option<T>>` (with `deserialize_with`) is avoided; nullable columns that must be clearable (`max_selections`) are handled by a dedicated presence flag pattern below.
    pub fn new() -> PatchGroupRequest {
        PatchGroupRequest {
            is_required: None,
            max_selections: None,
            min_selections: None,
            name: None,
            name_translations: None,
            selection_type: None,
            sort: None,
        }
    }
}

