/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PeakHourPoint {
    /// SUM(order_item_addons.quantity) across non-voided orders in this hour bucket.
    #[serde(rename = "addons")]
    pub addons: i64,
    /// Orders averaged over the number of calendar days (may be fractional).
    #[serde(rename = "avg_orders_per_day")]
    pub avg_orders_per_day: f64,
    /// Revenue in piastres averaged over the number of calendar days in the queried range.
    #[serde(rename = "avg_revenue_per_day")]
    pub avg_revenue_per_day: i64,
    #[serde(rename = "discount")]
    pub discount: i64,
    #[serde(rename = "hour")]
    pub hour: i32,
    /// SUM(order_items.quantity) across non-voided orders in this hour bucket.
    #[serde(rename = "line_items")]
    pub line_items: i64,
    #[serde(rename = "orders")]
    pub orders: i64,
    /// This hour's orders as a percentage of the period total (0–100, 1 dp).
    #[serde(rename = "orders_pct")]
    pub orders_pct: f64,
    #[serde(rename = "revenue")]
    pub revenue: i64,
    /// This hour's revenue as a percentage of the period total (0–100, 1 dp).
    #[serde(rename = "revenue_pct")]
    pub revenue_pct: f64,
    #[serde(rename = "tax")]
    pub tax: i64,
    #[serde(rename = "voided")]
    pub voided: i64,
}

impl PeakHourPoint {
    pub fn new(
        addons: i64,
        avg_orders_per_day: f64,
        avg_revenue_per_day: i64,
        discount: i64,
        hour: i32,
        line_items: i64,
        orders: i64,
        orders_pct: f64,
        revenue: i64,
        revenue_pct: f64,
        tax: i64,
        voided: i64,
    ) -> PeakHourPoint {
        PeakHourPoint {
            addons,
            avg_orders_per_day,
            avg_revenue_per_day,
            discount,
            hour,
            line_items,
            orders,
            orders_pct,
            revenue,
            revenue_pct,
            tax,
            voided,
        }
    }
}
