/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Preferences {
    /// Days I can't work: 0 = Sunday … 6 = Saturday.
    #[serde(rename = "cant_work_days", skip_serializing_if = "Option::is_none")]
    pub cant_work_days: Option<Vec<i32>>,
    /// Why (a manager's override).
    #[serde(
        rename = "note",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub note: Option<Option<String>>,
    /// `morning` · `evening` · null
    #[serde(
        rename = "pref_time",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pref_time: Option<Option<String>>,
}

impl Preferences {
    pub fn new() -> Preferences {
        Preferences {
            cant_work_days: None,
            note: None,
            pref_time: None,
        }
    }
}
