/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreviewPrice {
    /// Unit price of the item/size, piastres.
    #[serde(rename = "base")]
    pub base: i32,
    #[serde(rename = "options")]
    pub options: Vec<models::PreviewOptionPrice>,
    /// (base + options) × quantity, piastres.
    #[serde(rename = "total")]
    pub total: i32,
}

impl PreviewPrice {
    pub fn new(base: i32, options: Vec<models::PreviewOptionPrice>, total: i32) -> PreviewPrice {
        PreviewPrice {
            base,
            options,
            total,
        }
    }
}
