/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreviewRecipeRequest {
    #[serde(rename = "addons")]
    pub addons: Vec<models::PreviewAddonInput>,
    #[serde(rename = "menu_item_id")]
    pub menu_item_id: uuid::Uuid,
    #[serde(rename = "optional_field_ids")]
    pub optional_field_ids: Vec<uuid::Uuid>,
    #[serde(rename = "size_label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub size_label: Option<Option<String>>,
}

impl PreviewRecipeRequest {
    pub fn new(addons: Vec<models::PreviewAddonInput>, menu_item_id: uuid::Uuid, optional_field_ids: Vec<uuid::Uuid>) -> PreviewRecipeRequest {
        PreviewRecipeRequest {
            addons,
            menu_item_id,
            optional_field_ids,
            size_label: None,
        }
    }
}

