/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PriceAnchors : Two anchors are universal; the cost-plus anchor is only meaningful with cost data, so it's optional.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriceAnchors {
    #[serde(rename = "cost_plus", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cost_plus: Option<Option<f64>>,
    #[serde(rename = "peer_median")]
    pub peer_median: f64,
    #[serde(rename = "status_quo")]
    pub status_quo: f64,
}

impl PriceAnchors {
    /// Two anchors are universal; the cost-plus anchor is only meaningful with cost data, so it's optional.
    pub fn new(peer_median: f64, status_quo: f64) -> PriceAnchors {
        PriceAnchors {
            cost_plus: None,
            peer_median,
            status_quo,
        }
    }
}

