/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PublicBrand : A shop, as a guest page needs to know it.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicBrand {
    #[serde(rename = "accent_color")]
    pub accent_color: String,
    /// `#RRGGBB`. Madar's own when the shop is not on the tier.
    #[serde(rename = "background_color")]
    pub background_color: String,
    #[serde(rename = "card_image_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub card_image_url: Option<Option<String>>,
    /// Whether the rest of this is the shop's or Madar's.  The page does not need it to render — the palette below is already resolved — but it decides how loudly Madar signs the footer.
    #[serde(rename = "custom_branding")]
    pub custom_branding: bool,
    #[serde(rename = "foreground_color")]
    pub foreground_color: String,
    /// True when the logo is a shape on transparency and may be repainted for contrast. See `orgs::branding::is_mark`.
    #[serde(rename = "logo_is_mark")]
    pub logo_is_mark: bool,
    #[serde(rename = "logo_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logo_url: Option<Option<String>>,
    /// Always the shop's own name, at every tier. A page that does not say whose it is helps nobody, and that was never the thing being sold.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "slug")]
    pub slug: String,
}

impl PublicBrand {
    /// A shop, as a guest page needs to know it.
    pub fn new(accent_color: String, background_color: String, custom_branding: bool, foreground_color: String, logo_is_mark: bool, name: String, org_id: uuid::Uuid, slug: String) -> PublicBrand {
        PublicBrand {
            accent_color,
            background_color,
            card_image_url: None,
            custom_branding,
            foreground_color,
            logo_is_mark,
            logo_url: None,
            name,
            org_id,
            slug,
        }
    }
}

