/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PublicTable : A table, as the page that opened from its code needs to know it.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicTable {
    /// The branch is not serving right now — no till is open. The page says so instead of letting someone build a basket the kitchen will refuse.
    #[serde(rename = "accepting")]
    pub accepting: bool,
    /// The meal in progress, when there is one. `None` means the table is free and this scan will start the bill.
    #[serde(
        rename = "bill",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub bill: Option<Option<Box<models::PublicTableBill>>>,
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "branch_name")]
    pub branch_name: String,
    /// What the table is called in the room — \"7\", \"T7\", \"Terrace 2\".
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "table_id")]
    pub table_id: uuid::Uuid,
}

impl PublicTable {
    /// A table, as the page that opened from its code needs to know it.
    pub fn new(
        accepting: bool,
        branch_id: uuid::Uuid,
        branch_name: String,
        label: String,
        org_id: uuid::Uuid,
        table_id: uuid::Uuid,
    ) -> PublicTable {
        PublicTable {
            accepting,
            bill: None,
            branch_id,
            branch_name,
            label,
            org_id,
            table_id,
        }
    }
}
