/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PublicComboSize : A size of a public combo choice.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicComboSize {
    /// What picking it adds inside the combo (the owner's surcharge, else the difference over the included size, floored at 0; 0 for the included size).
    #[serde(rename = "extra")]
    pub extra: i32,
    #[serde(rename = "label")]
    pub label: String,
    /// Its normal channel price.
    #[serde(rename = "price")]
    pub price: i32,
}

impl PublicComboSize {
    /// A size of a public combo choice.
    pub fn new(extra: i32, label: String, price: i32) -> PublicComboSize {
        PublicComboSize {
            extra,
            label,
            price,
        }
    }
}
