/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullChange {
    #[serde(rename = "data")]
    pub data: serde_json::Value,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    /// `upsert` | `delete`.
    #[serde(rename = "op")]
    pub op: String,
    #[serde(rename = "seq")]
    pub seq: i64,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl PullChange {
    pub fn new(
        data: serde_json::Value,
        id: uuid::Uuid,
        op: String,
        seq: i64,
        r#type: String,
    ) -> PullChange {
        PullChange {
            data,
            id,
            op,
            seq,
            r#type,
        }
    }
}
