/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullRequest {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(
        rename = "device_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub device_id: Option<Option<uuid::Uuid>>,
    /// Opt-in paging of a FULL snapshot's ledger rows (tills, orders, cash, refunds), 100..10000 rows a page. Absent = the whole snapshot in one response (what every older client gets).
    #[serde(
        rename = "ledger_page_size",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ledger_page_size: Option<Option<i64>>,
    /// Page size for incremental pulls, 1..5000 (default 2000).
    #[serde(
        rename = "limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub limit: Option<Option<i64>>,
    /// The `snapshot_cursor` of the previous page of a paged full snapshot.
    #[serde(
        rename = "snapshot_cursor",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub snapshot_cursor: Option<Option<Box<models::SnapshotCursor>>>,
    /// Full-fetch ONLY these types (checksum self-heal). Invalid with `since`.
    #[serde(
        rename = "types",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub types: Option<Option<Vec<String>>>,
}

impl PullRequest {
    pub fn new(branch_id: uuid::Uuid) -> PullRequest {
        PullRequest {
            branch_id,
            device_id: None,
            ledger_page_size: None,
            limit: None,
            snapshot_cursor: None,
            types: None,
        }
    }
}
