/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PunchFor {
    #[serde(rename = "employee_id")]
    pub employee_id: uuid::Uuid,
    /// Set when the manager's phone queued the punch offline: it is dated at its own time, not when the phone got a signal back (audit 03 bug 6).
    #[serde(
        rename = "offline",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub offline: Option<Option<Box<models::OfflineStamp>>>,
    /// Required (CL-13): a dead phone, a forgotten one. Missing reads as blank, so the answer is \"A reason is required.\" (Mac E2E BC-4).
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl PunchFor {
    pub fn new(employee_id: uuid::Uuid) -> PunchFor {
        PunchFor {
            employee_id,
            offline: None,
            reason: None,
        }
    }
}
