/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutEarningItems {
    #[serde(
        rename = "branch_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub branch_id: Option<Option<uuid::Uuid>>,
    /// The complete list for this scope, in order. An empty list clears it: for an org that means every item collects again, for a branch it means going back to inheriting the org's.
    #[serde(rename = "menu_item_ids")]
    pub menu_item_ids: Vec<uuid::Uuid>,
}

impl PutEarningItems {
    pub fn new(menu_item_ids: Vec<uuid::Uuid>) -> PutEarningItems {
        PutEarningItems {
            branch_id: None,
            menu_item_ids,
        }
    }
}
