/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutOverrideRequest {
    #[serde(rename = "on_date")]
    pub on_date: chrono::NaiveDate,
    #[serde(
        rename = "reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reason: Option<Option<String>>,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
    /// Omit (or send null) to mark the date an explicit day off.
    #[serde(
        rename = "work_shift_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub work_shift_id: Option<Option<uuid::Uuid>>,
}

impl PutOverrideRequest {
    pub fn new(on_date: chrono::NaiveDate, user_id: uuid::Uuid) -> PutOverrideRequest {
        PutOverrideRequest {
            on_date,
            reason: None,
            user_id,
            work_shift_id: None,
        }
    }
}
