/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutAttendanceSettingsRequest {
    #[serde(
        rename = "absence_deduction_days",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub absence_deduction_days: Option<Option<f64>>,
    #[serde(
        rename = "advance_cap_percent",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub advance_cap_percent: Option<Option<f64>>,
    #[serde(
        rename = "auto_checkout_buffer_minutes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub auto_checkout_buffer_minutes: Option<Option<i32>>,
    /// `None` = the org-wide default row.
    #[serde(
        rename = "branch_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub branch_id: Option<Option<uuid::Uuid>>,
    /// `minute_rate` · `full_block` (D5). On a branch: its own override; `inherit: [\"cover_pay_mode\"]` goes back to the business's.
    #[serde(
        rename = "cover_pay_mode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cover_pay_mode: Option<Option<String>>,
    #[serde(
        rename = "default_overtime_multiplier",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_overtime_multiplier: Option<Option<f64>>,
    #[serde(
        rename = "excused_time_paid_default",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub excused_time_paid_default: Option<Option<bool>>,
    /// `off` · `soft` · `hard`; owner only (`hr.roster.settings`).
    #[serde(
        rename = "gender_mode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub gender_mode: Option<Option<String>>,
    /// `half_shift` · `whole_day`.
    #[serde(
        rename = "half_day_leave_counts",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub half_day_leave_counts: Option<Option<String>>,
    #[serde(
        rename = "holiday_multiplier",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub holiday_multiplier: Option<Option<f64>>,
    /// Branch only: rules to take from the business again (field names, as in `overridden`).
    #[serde(
        rename = "inherit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub inherit: Option<Option<Vec<String>>>,
    #[serde(
        rename = "late_deduction_tiers",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub late_deduction_tiers: Option<Option<Vec<models::LateTier>>>,
    #[serde(
        rename = "limit_day_hours",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub limit_day_hours: Option<Option<f64>>,
    #[serde(
        rename = "limit_overtime_day_hours",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub limit_overtime_day_hours: Option<Option<f64>>,
    #[serde(
        rename = "limit_presence_hours",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub limit_presence_hours: Option<Option<f64>>,
    #[serde(
        rename = "limit_rest_hours",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub limit_rest_hours: Option<Option<f64>>,
    #[serde(
        rename = "limit_week_hours",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub limit_week_hours: Option<Option<f64>>,
    #[serde(
        rename = "night_end",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub night_end: Option<Option<String>>,
    #[serde(
        rename = "night_start",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub night_start: Option<Option<String>>,
    #[serde(
        rename = "orders_per_staff",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub orders_per_staff: Option<Option<i32>>,
    #[serde(
        rename = "overtime_day_multiplier",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub overtime_day_multiplier: Option<Option<f64>>,
    /// `off` · `automatic` · `approval`.
    #[serde(
        rename = "overtime_mode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub overtime_mode: Option<Option<String>>,
    #[serde(
        rename = "overtime_night_multiplier",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub overtime_night_multiplier: Option<Option<f64>>,
    #[serde(
        rename = "period_start_day",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub period_start_day: Option<Option<i32>>,
    #[serde(
        rename = "require_geofence",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub require_geofence: Option<Option<bool>>,
    #[serde(
        rename = "working_days_per_month",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub working_days_per_month: Option<Option<f64>>,
}

impl PutAttendanceSettingsRequest {
    pub fn new() -> PutAttendanceSettingsRequest {
        PutAttendanceSettingsRequest {
            absence_deduction_days: None,
            advance_cap_percent: None,
            auto_checkout_buffer_minutes: None,
            branch_id: None,
            cover_pay_mode: None,
            default_overtime_multiplier: None,
            excused_time_paid_default: None,
            gender_mode: None,
            half_day_leave_counts: None,
            holiday_multiplier: None,
            inherit: None,
            late_deduction_tiers: None,
            limit_day_hours: None,
            limit_overtime_day_hours: None,
            limit_presence_hours: None,
            limit_rest_hours: None,
            limit_week_hours: None,
            night_end: None,
            night_start: None,
            orders_per_staff: None,
            overtime_day_multiplier: None,
            overtime_mode: None,
            overtime_night_multiplier: None,
            period_start_day: None,
            require_geofence: None,
            working_days_per_month: None,
        }
    }
}
