/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QrResponse : JSON returned from every QR-generation endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QrResponse {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "long_url")]
    pub long_url: String,
    /// `data:image/png;base64,…` (or `data:image/svg+xml;base64,…` when `svg=true`).  Paste into a browser `<img src=\"…\">` to verify.
    #[serde(rename = "qr_data_url")]
    pub qr_data_url: String,
    #[serde(rename = "short_code")]
    pub short_code: String,
    #[serde(rename = "short_url")]
    pub short_url: String,
}

impl QrResponse {
    /// JSON returned from every QR-generation endpoint.
    pub fn new(kind: String, long_url: String, qr_data_url: String, short_code: String, short_url: String) -> QrResponse {
        QrResponse {
            kind,
            long_url,
            qr_data_url,
            short_code,
            short_url,
        }
    }
}

