/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotedLine {
    #[serde(
        rename = "combo",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub combo: Option<Option<Box<models::QuotedCombo>>>,
    /// What the applied deals took off this line.
    #[serde(rename = "deal_minor")]
    pub deal_minor: i32,
    /// Index into the request's `items[]`.
    #[serde(rename = "index")]
    pub index: i32,
    /// The whole line with its add-ons, before deals.
    #[serde(rename = "line_total")]
    pub line_total: i32,
    #[serde(rename = "quantity")]
    pub quantity: i32,
    /// The size price per unit (a combo: 0; see `combo`).
    #[serde(rename = "unit_price")]
    pub unit_price: i32,
}

impl QuotedLine {
    pub fn new(
        deal_minor: i32,
        index: i32,
        line_total: i32,
        quantity: i32,
        unit_price: i32,
    ) -> QuotedLine {
        QuotedLine {
            combo: None,
            deal_minor,
            index,
            line_total,
            quantity,
            unit_price,
        }
    }
}
