/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuoteResponse {
    #[serde(
        rename = "distance_meters",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub distance_meters: Option<Option<i32>>,
    #[serde(
        rename = "fee",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub fee: Option<Option<i32>>,
    /// \"ok\" | \"out_of_range\" | \"unavailable\"
    #[serde(rename = "status")]
    pub status: String,
    /// The tax the cart will be priced under at this branch. A quote is a fee quote — it has no cart, so no tax amount — but the page rendering the checkout total needs the rate and the inclusivity beside the fee, or it shows the customer one number and intake records another. Present on every outcome: the policy is the branch's, not the address's.
    #[serde(rename = "tax_policy")]
    pub tax_policy: Box<models::OnlineTaxPolicy>,
    #[serde(
        rename = "zone_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub zone_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "zone_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub zone_name: Option<Option<String>>,
}

impl QuoteResponse {
    pub fn new(status: String, tax_policy: models::OnlineTaxPolicy) -> QuoteResponse {
        QuoteResponse {
            distance_meters: None,
            fee: None,
            status,
            tax_policy: Box::new(tax_policy),
            zone_id: None,
            zone_name: None,
        }
    }
}
