/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QuotedDeal : A deal the server applied to the cart.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QuotedDeal {
    #[serde(rename = "deal_rule_id")]
    pub deal_rule_id: uuid::Uuid,
    #[serde(rename = "discount")]
    pub discount: i32,
    #[serde(rename = "lines")]
    pub lines: Vec<models::DealLineInput>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_translations")]
    pub name_translations: serde_json::Value,
    #[serde(rename = "times")]
    pub times: i32,
}

impl QuotedDeal {
    /// A deal the server applied to the cart.
    pub fn new(
        deal_rule_id: uuid::Uuid,
        discount: i32,
        lines: Vec<models::DealLineInput>,
        name: String,
        name_translations: serde_json::Value,
        times: i32,
    ) -> QuotedDeal {
        QuotedDeal {
            deal_rule_id,
            discount,
            lines,
            name,
            name_translations,
            times,
        }
    }
}
