/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecipeLinkInfo : Link state of an item, from either side.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecipeLinkInfo {
    /// For a copy: `true` when its stored lines equal the source's for every size label the copy has (lint F19, twin drift). `null` for an item that is not a copy.
    #[serde(
        rename = "in_sync",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub in_sync: Option<Option<bool>>,
    /// Live items whose recipe follows this one.
    #[serde(rename = "linked_copy_ids")]
    pub linked_copy_ids: Vec<uuid::Uuid>,
    #[serde(rename = "menu_item_id")]
    pub menu_item_id: uuid::Uuid,
    /// The item this one's recipe follows, or `null`.
    #[serde(
        rename = "recipe_source_item_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub recipe_source_item_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "recipe_source_item_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub recipe_source_item_name: Option<Option<String>>,
}

impl RecipeLinkInfo {
    /// Link state of an item, from either side.
    pub fn new(linked_copy_ids: Vec<uuid::Uuid>, menu_item_id: uuid::Uuid) -> RecipeLinkInfo {
        RecipeLinkInfo {
            in_sync: None,
            linked_copy_ids,
            menu_item_id,
            recipe_source_item_id: None,
            recipe_source_item_name: None,
        }
    }
}
