/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecipeStepPreset : One curated step the dashboard offers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecipeStepPreset {
    /// Content hash of the zstd-compressed asset (`/assets/global/<hash>.lottie.zst`).
    #[serde(
        rename = "animation_hash",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub animation_hash: Option<Option<String>>,
    #[serde(rename = "animation_sha256")]
    pub animation_sha256: String,
    /// Path to the animation, relative to the API base.
    #[serde(rename = "animation_url")]
    pub animation_url: String,
    #[serde(rename = "bytes")]
    pub bytes: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_ar")]
    pub name_ar: String,
    #[serde(
        rename = "note",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub note: Option<Option<String>>,
    #[serde(
        rename = "note_ar",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub note_ar: Option<Option<String>>,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "sort_order")]
    pub sort_order: i32,
}

impl RecipeStepPreset {
    /// One curated step the dashboard offers.
    pub fn new(
        animation_sha256: String,
        animation_url: String,
        bytes: i32,
        name: String,
        name_ar: String,
        slug: String,
        sort_order: i32,
    ) -> RecipeStepPreset {
        RecipeStepPreset {
            animation_hash: None,
            animation_sha256,
            animation_url,
            bytes,
            name,
            name_ar,
            note: None,
            note_ar: None,
            slug,
            sort_order,
        }
    }
}
