/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecipeBaseLineInput : A line as submitted: quantity in `unit`, normalized to the ingredient's base unit (and grossed up by yield) exactly like a size recipe line.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecipeBaseLineInput {
    #[serde(rename = "ingredient_id")]
    pub ingredient_id: uuid::Uuid,
    #[serde(rename = "quantity")]
    pub quantity: f64,
    #[serde(
        rename = "size_label",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub size_label: Option<Option<String>>,
    #[serde(
        rename = "sort",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sort: Option<Option<i32>>,
    #[serde(rename = "unit")]
    pub unit: String,
}

impl RecipeBaseLineInput {
    /// A line as submitted: quantity in `unit`, normalized to the ingredient's base unit (and grossed up by yield) exactly like a size recipe line.
    pub fn new(ingredient_id: uuid::Uuid, quantity: f64, unit: String) -> RecipeBaseLineInput {
        RecipeBaseLineInput {
            ingredient_id,
            quantity,
            size_label: None,
            sort: None,
            unit,
        }
    }
}
