/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RefundReason : Why money went back. The first three share their spelling with [`crate::orders::VoidReason`] so a report reads \"wrong order\" across voids and refunds alike; the rest exist only for refunds (you do not void a sale for being late). Bound as text; the table's CHECK is the authority on the vocabulary and this enum mirrors it.
/// Why money went back. The first three share their spelling with [`crate::orders::VoidReason`] so a report reads \"wrong order\" across voids and refunds alike; the rest exist only for refunds (you do not void a sale for being late). Bound as text; the table's CHECK is the authority on the vocabulary and this enum mirrors it.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RefundReason {
    #[serde(rename = "customer_request")]
    CustomerRequest,
    #[serde(rename = "wrong_order")]
    WrongOrder,
    #[serde(rename = "quality_issue")]
    QualityIssue,
    #[serde(rename = "overcharged")]
    Overcharged,
    #[serde(rename = "late_or_undelivered")]
    LateOrUndelivered,
    #[serde(rename = "goodwill")]
    Goodwill,
    #[serde(rename = "other")]
    Other,
}

impl std::fmt::Display for RefundReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CustomerRequest => write!(f, "customer_request"),
            Self::WrongOrder => write!(f, "wrong_order"),
            Self::QualityIssue => write!(f, "quality_issue"),
            Self::Overcharged => write!(f, "overcharged"),
            Self::LateOrUndelivered => write!(f, "late_or_undelivered"),
            Self::Goodwill => write!(f, "goodwill"),
            Self::Other => write!(f, "other"),
        }
    }
}

impl Default for RefundReason {
    fn default() -> RefundReason {
        Self::CustomerRequest
    }
}
