/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemovalScenario {
    #[serde(rename = "absorbed_by")]
    pub absorbed_by: Vec<models::AbsorbedBy>,
    #[serde(rename = "baseline_cm")]
    pub baseline_cm: f64,
    #[serde(rename = "complementary_losses")]
    pub complementary_losses: Vec<models::ComplementaryLoss>,
    #[serde(rename = "explanation")]
    pub explanation: String,
    #[serde(rename = "item_name")]
    pub item_name: String,
    #[serde(rename = "key")]
    pub key: Box<models::ItemKey>,
    #[serde(rename = "net_cm_change")]
    pub net_cm_change: f64,
    #[serde(rename = "net_cm_change_hi")]
    pub net_cm_change_hi: f64,
    #[serde(rename = "net_cm_change_lo")]
    pub net_cm_change_lo: f64,
    #[serde(rename = "recommendation")]
    pub recommendation: models::RemovalRecommendation,
}

impl RemovalScenario {
    pub fn new(absorbed_by: Vec<models::AbsorbedBy>, baseline_cm: f64, complementary_losses: Vec<models::ComplementaryLoss>, explanation: String, item_name: String, key: models::ItemKey, net_cm_change: f64, net_cm_change_hi: f64, net_cm_change_lo: f64, recommendation: models::RemovalRecommendation) -> RemovalScenario {
        RemovalScenario {
            absorbed_by,
            baseline_cm,
            complementary_losses,
            explanation,
            item_name,
            key: Box::new(key),
            net_cm_change,
            net_cm_change_hi,
            net_cm_change_lo,
            recommendation,
        }
    }
}

