/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReorderLine : One ingredient to reorder, with the quantity needed to reach its order-up-to level (par_max, else the reorder point).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReorderLine {
    #[serde(rename = "current_stock")]
    pub current_stock: f64,
    #[serde(rename = "ingredient_name")]
    pub ingredient_name: String,
    #[serde(rename = "org_ingredient_id")]
    pub org_ingredient_id: uuid::Uuid,
    /// Quantity (in base units) to bring stock up to the order-up-to level.
    #[serde(rename = "suggested_qty")]
    pub suggested_qty: f64,
    #[serde(rename = "unit")]
    pub unit: String,
}

impl ReorderLine {
    /// One ingredient to reorder, with the quantity needed to reach its order-up-to level (par_max, else the reorder point).
    pub fn new(current_stock: f64, ingredient_name: String, org_ingredient_id: uuid::Uuid, suggested_qty: f64, unit: String) -> ReorderLine {
        ReorderLine {
            current_stock,
            ingredient_name,
            org_ingredient_id,
            suggested_qty,
            unit,
        }
    }
}

