/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReservationSettings {
    #[serde(rename = "accepting_reservations")]
    pub accepting_reservations: bool,
    #[serde(rename = "accepting_waitlist")]
    pub accepting_waitlist: bool,
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "grace_minutes")]
    pub grace_minutes: i32,
    #[serde(rename = "hold_lead_minutes")]
    pub hold_lead_minutes: i32,
    #[serde(rename = "lead_minutes")]
    pub lead_minutes: i32,
    #[serde(rename = "max_party_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_party_size: Option<Option<i32>>,
    #[serde(rename = "slot_minutes")]
    pub slot_minutes: i32,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl ReservationSettings {
    pub fn new(accepting_reservations: bool, accepting_waitlist: bool, branch_id: uuid::Uuid, grace_minutes: i32, hold_lead_minutes: i32, lead_minutes: i32, slot_minutes: i32, updated_at: chrono::DateTime<chrono::FixedOffset>) -> ReservationSettings {
        ReservationSettings {
            accepting_reservations,
            accepting_waitlist,
            branch_id,
            grace_minutes,
            hold_lead_minutes,
            lead_minutes,
            max_party_size: None,
            slot_minutes,
            updated_at,
        }
    }
}

