/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReturnLineInput {
    #[serde(rename = "org_ingredient_id")]
    pub org_ingredient_id: uuid::Uuid,
    /// Base stock units to return (must be ≤ on hand).
    #[serde(rename = "quantity")]
    pub quantity: f64,
    /// Piastres per base stock unit; defaults to the branch's actual cost.
    #[serde(rename = "unit_cost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unit_cost: Option<Option<i64>>,
}

impl ReturnLineInput {
    pub fn new(org_ingredient_id: uuid::Uuid, quantity: f64) -> ReturnLineInput {
        ReturnLineInput {
            org_ingredient_id,
            quantity,
            unit_cost: None,
        }
    }
}

