/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RosterShift {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    /// Changed after its week was published (SC-4).
    #[serde(rename = "changed")]
    pub changed: bool,
    #[serde(rename = "date")]
    pub date: chrono::NaiveDate,
    #[serde(rename = "employee_id")]
    pub employee_id: uuid::Uuid,
    #[serde(rename = "employee_name")]
    pub employee_name: String,
    #[serde(rename = "end_at")]
    pub end_at: chrono::DateTime<chrono::FixedOffset>,
    /// On approved leave or a mission that day.
    #[serde(rename = "on_leave")]
    pub on_leave: bool,
    #[serde(rename = "shift_name")]
    pub shift_name: String,
    #[serde(rename = "start_at")]
    pub start_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "work_shift_id")]
    pub work_shift_id: uuid::Uuid,
}

impl RosterShift {
    pub fn new(
        branch_id: uuid::Uuid,
        changed: bool,
        date: chrono::NaiveDate,
        employee_id: uuid::Uuid,
        employee_name: String,
        end_at: chrono::DateTime<chrono::FixedOffset>,
        on_leave: bool,
        shift_name: String,
        start_at: chrono::DateTime<chrono::FixedOffset>,
        work_shift_id: uuid::Uuid,
    ) -> RosterShift {
        RosterShift {
            branch_id,
            changed,
            date,
            employee_id,
            employee_name,
            end_at,
            on_leave,
            shift_name,
            start_at,
            work_shift_id,
        }
    }
}
