/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoutingModeResponse {
    /// What actually applies right now (auto resolves to kds-if-stations-else-till).
    #[serde(rename = "effective")]
    pub effective: String,
    /// Stored override (`kds` | `till` | `both`), or null when auto.
    #[serde(rename = "mode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Option<String>>,
}

impl RoutingModeResponse {
    pub fn new(effective: String) -> RoutingModeResponse {
        RoutingModeResponse {
            effective,
            mode: None,
        }
    }
}

