/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SalaryAdvanceRow {
    #[serde(rename = "amount_piastres")]
    pub amount_piastres: i64,
    #[serde(rename = "employee_id")]
    pub employee_id: uuid::Uuid,
    #[serde(rename = "employee_name")]
    pub employee_name: String,
    #[serde(rename = "given_on")]
    pub given_on: chrono::NaiveDate,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "installments")]
    pub installments: i32,
    #[serde(rename = "remaining_piastres")]
    pub remaining_piastres: i64,
    /// `pending` · `approved` · `rejected` · …
    #[serde(rename = "status")]
    pub status: String,
}

impl SalaryAdvanceRow {
    pub fn new(
        amount_piastres: i64,
        employee_id: uuid::Uuid,
        employee_name: String,
        given_on: chrono::NaiveDate,
        id: uuid::Uuid,
        installments: i32,
        remaining_piastres: i64,
        status: String,
    ) -> SalaryAdvanceRow {
        SalaryAdvanceRow {
            amount_piastres,
            employee_id,
            employee_name,
            given_on,
            id,
            installments,
            remaining_piastres,
            status,
        }
    }
}
