/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetRoutingModeRequest {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    /// `kds` | `till` | `both`, or null to clear the override (back to auto).
    #[serde(rename = "mode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Option<String>>,
}

impl SetRoutingModeRequest {
    pub fn new(branch_id: uuid::Uuid) -> SetRoutingModeRequest {
        SetRoutingModeRequest {
            branch_id,
            mode: None,
        }
    }
}

