/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettleOpenTicketRequest {
    #[serde(
        rename = "amount_tendered",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub amount_tendered: Option<Option<i32>>,
    /// What the till handed back. Recorded as the drawer saw it, like a counter sale's; absent, it is derived from `amount_tendered` and the server's total.
    #[serde(
        rename = "change_given",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub change_given: Option<Option<i32>>,
    /// What the till actually took off this bill, in minor units — the figure the drawer charged. Additive; absent, the server computes it as before. This is also what a replayed bill keeps when its preset has since been switched off: the money as rung, never recomputed from a dead rule.
    #[serde(
        rename = "discount_amount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discount_amount: Option<Option<i32>>,
    /// Who put the discount on the bill. Read on replay (live, it is the cashier holding the token). Additive.
    #[serde(
        rename = "discount_applied_by",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discount_applied_by: Option<Option<uuid::Uuid>>,
    /// The manager approval that let the bill's discount past the cashier's cap, verified at replay like a counter sale's. Additive.
    #[serde(
        rename = "discount_approval_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discount_approval_id: Option<Option<uuid::Uuid>>,
    /// Settle-time discount. ABSENT (all three fields) means the waiter's ticket discount is inherited, as it always was — but the till can now see that discount on the ticket view. The literal `discount_type: \"none\"` settles with no discount at all; any other value (or a `discount_id`) replaces the waiter's.
    #[serde(
        rename = "discount_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discount_id: Option<Option<uuid::Uuid>>,
    /// Which discount act this bill performs: `preset` | `manual_amount` | `manual_percent`. A table bill is gated exactly like a counter sale, so it names its act in the same vocabulary. ADDITIVE — an older tablet sends nothing and the kind is derived as it always was (a `discount_id` means preset, an ad-hoc discount is manual of its type).
    #[serde(
        rename = "discount_kind",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discount_kind: Option<Option<String>>,
    /// Basis points for a percentage bill discount (1250 = 12.5%). Additive.
    #[serde(
        rename = "discount_percent_bps",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discount_percent_bps: Option<Option<i32>>,
    #[serde(
        rename = "discount_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discount_type: Option<Option<String>>,
    #[serde(
        rename = "discount_value",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub discount_value: Option<Option<f64>>,
    /// The member spending a balance on this settle, when rewards are applied.
    #[serde(
        rename = "loyalty_customer_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub loyalty_customer_id: Option<Option<uuid::Uuid>>,
    /// Rewards covering lines of the ticket. A table-service bill redeems exactly like a counter one — the cashier scans at settle either way.
    #[serde(
        rename = "loyalty_redemptions",
        skip_serializing_if = "Option::is_none"
    )]
    pub loyalty_redemptions: Option<Vec<models::LoyaltyRedemptionInput>>,
    #[serde(rename = "payment_method")]
    pub payment_method: String,
    /// Split tenders, when the party paid with more than one. Carried to the order's payment legs like a counter sale's; they must sum to the total.
    #[serde(
        rename = "payment_splits",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub payment_splits: Option<Option<Vec<models::PaymentSplitInput>>>,
    /// When the bill was paid, as the till says. An offline settle replayed later keeps its real time — it becomes the order's `created_at` and the ticket's `settled_at`, one instant on both rows. Absent means now; a future clock is refused.
    #[serde(
        rename = "settled_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub settled_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "till_id")]
    pub till_id: uuid::Uuid,
    #[serde(
        rename = "tip_amount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tip_amount: Option<Option<i32>>,
    #[serde(
        rename = "tip_payment_method",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tip_payment_method: Option<Option<String>>,
    /// What the till says the bill came to — the figure its drawer collected. Checked against the server's own total exactly as a counter checkout is (`create_order_inner`'s drift check); a disagreement is refused, not recorded. Absent on older builds, which then get no check. The figure to send is `OpenTicketView::bill.total`, which is priced by the same engine under the same policy — a till that shows that number cannot disagree with the books.
    #[serde(
        rename = "total_amount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_amount: Option<Option<i32>>,
    /// Remove the service charge from this bill. Only someone whose effective permissions include `orders:waive_service` may send `true`; anyone else is refused, live or replayed. The order records who and when. Absent (every build before 0.7.2) means the charge stands.
    #[serde(
        rename = "waive_service_charge",
        skip_serializing_if = "Option::is_none"
    )]
    pub waive_service_charge: Option<bool>,
}

impl SettleOpenTicketRequest {
    pub fn new(payment_method: String, till_id: uuid::Uuid) -> SettleOpenTicketRequest {
        SettleOpenTicketRequest {
            amount_tendered: None,
            change_given: None,
            discount_amount: None,
            discount_applied_by: None,
            discount_approval_id: None,
            discount_id: None,
            discount_kind: None,
            discount_percent_bps: None,
            discount_type: None,
            discount_value: None,
            loyalty_customer_id: None,
            loyalty_redemptions: None,
            payment_method,
            payment_splits: None,
            settled_at: None,
            till_id,
            tip_amount: None,
            tip_payment_method: None,
            total_amount: None,
            waive_service_charge: None,
        }
    }
}
