/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShiftSummary {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "branch_name")]
    pub branch_name: String,
    #[serde(
        rename = "cash_discrepancy",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cash_discrepancy: Option<Option<i64>>,
    /// The cash slice of `total_tips`.
    #[serde(rename = "cash_tips", skip_serializing_if = "Option::is_none")]
    pub cash_tips: Option<i64>,
    #[serde(
        rename = "closed_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub closed_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(
        rename = "closing_cash_declared",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub closing_cash_declared: Option<Option<i64>>,
    #[serde(
        rename = "closing_cash_system",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub closing_cash_system: Option<Option<i64>>,
    /// This shift's sales as rung up, before any refund. Was what `total_revenue` meant until 2026-09.
    #[serde(rename = "gross_sales", skip_serializing_if = "Option::is_none")]
    pub gross_sales: Option<i64>,
    #[serde(rename = "opened_at")]
    pub opened_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "opening_cash")]
    pub opening_cash: i64,
    /// Money refunded AGAINST this shift's sales, whenever and from whichever drawer it was issued. `gross_sales − refunded_amount = total_revenue`. A fully refunded sale is out of all three (its status is `refunded`).
    #[serde(rename = "refunded_amount", skip_serializing_if = "Option::is_none")]
    pub refunded_amount: Option<i64>,
    #[serde(
        rename = "refunds_issued_amount",
        skip_serializing_if = "Option::is_none"
    )]
    pub refunds_issued_amount: Option<i64>,
    #[serde(
        rename = "refunds_issued_cash",
        skip_serializing_if = "Option::is_none"
    )]
    pub refunds_issued_cash: Option<i64>,
    /// Refunds ISSUED IN THIS SHIFT — keyed on `order_refunds.shift_id`, the drawer the money left, which need not be the shift that made the sale. This is the Z-report's money-out line: `refunds_issued_cash` is what the drawer is short by relative to its cash sales.
    #[serde(
        rename = "refunds_issued_count",
        skip_serializing_if = "Option::is_none"
    )]
    pub refunds_issued_count: Option<i64>,
    /// Goods only, by method actually tendered — money IN. Tips are in `total_tips`; refunds are not netted from these buckets (they are money OUT, with their own tender — see `refunds_issued_*`).
    #[serde(rename = "revenue_by_method", deserialize_with = "Option::deserialize")]
    pub revenue_by_method: Option<serde_json::Value>,
    #[serde(rename = "shift_id")]
    pub shift_id: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "teller_id")]
    pub teller_id: uuid::Uuid,
    #[serde(rename = "teller_name")]
    pub teller_name: String,
    /// Delivery fees on this shift's sales. Inside `total_revenue` (the customer paid them) but outside the tax base and not food revenue.
    #[serde(
        rename = "total_delivery_fees",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_delivery_fees: Option<i64>,
    #[serde(rename = "total_discount")]
    pub total_discount: i64,
    #[serde(rename = "total_orders")]
    pub total_orders: i64,
    /// What this shift's sales are worth after refunds: `gross_sales` less `refunded_amount`. Same definition as `total_revenue` on the branch sales report, so the two reconcile.
    #[serde(rename = "total_revenue")]
    pub total_revenue: i64,
    /// Service charge added to this shift's dine-in bills. Inside `total_revenue` as the shop's income; see `analytics::schema` for why.
    #[serde(
        rename = "total_service_charge",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_service_charge: Option<i64>,
    #[serde(rename = "total_tax")]
    pub total_tax: i64,
    /// Tips, standalone — matches `total_tips` on `GET /shifts/{id}/report`.
    #[serde(rename = "total_tips", skip_serializing_if = "Option::is_none")]
    pub total_tips: Option<i64>,
    #[serde(rename = "voided_orders")]
    pub voided_orders: i64,
}

impl ShiftSummary {
    pub fn new(
        branch_id: uuid::Uuid,
        branch_name: String,
        opened_at: chrono::DateTime<chrono::FixedOffset>,
        opening_cash: i64,
        revenue_by_method: Option<serde_json::Value>,
        shift_id: uuid::Uuid,
        status: String,
        teller_id: uuid::Uuid,
        teller_name: String,
        total_discount: i64,
        total_orders: i64,
        total_revenue: i64,
        total_tax: i64,
        voided_orders: i64,
    ) -> ShiftSummary {
        ShiftSummary {
            branch_id,
            branch_name,
            cash_discrepancy: None,
            cash_tips: None,
            closed_at: None,
            closing_cash_declared: None,
            closing_cash_system: None,
            gross_sales: None,
            opened_at,
            opening_cash,
            refunded_amount: None,
            refunds_issued_amount: None,
            refunds_issued_cash: None,
            refunds_issued_count: None,
            revenue_by_method,
            shift_id,
            status,
            teller_id,
            teller_name,
            total_delivery_fees: None,
            total_discount,
            total_orders,
            total_revenue,
            total_service_charge: None,
            total_tax,
            total_tips: None,
            voided_orders,
        }
    }
}
