/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShiftReportResponse {
    #[serde(rename = "cash_adjustments")]
    pub cash_adjustments: i64,
    #[serde(
        rename = "cash_in_refunded_sales",
        skip_serializing_if = "Option::is_none"
    )]
    pub cash_in_refunded_sales: Option<i64>,
    #[serde(rename = "cash_movements")]
    pub cash_movements: Vec<models::CashMovementSummaryRow>,
    #[serde(rename = "cash_movements_in")]
    pub cash_movements_in: i64,
    #[serde(rename = "cash_movements_net")]
    pub cash_movements_net: i64,
    #[serde(rename = "cash_movements_out")]
    pub cash_movements_out: i64,
    #[serde(rename = "cash_tips")]
    pub cash_tips: i64,
    #[serde(rename = "expected_cash")]
    pub expected_cash: i64,
    #[serde(rename = "net_payments")]
    pub net_payments: i64,
    #[serde(rename = "non_cash_tips")]
    pub non_cash_tips: i64,
    #[serde(rename = "payment_summary")]
    pub payment_summary: Vec<models::PaymentSummaryRow>,
    #[serde(rename = "printed_at")]
    pub printed_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(
        rename = "refunds_issued_amount",
        skip_serializing_if = "Option::is_none"
    )]
    pub refunds_issued_amount: Option<i64>,
    #[serde(
        rename = "refunds_issued_cash",
        skip_serializing_if = "Option::is_none"
    )]
    pub refunds_issued_cash: Option<i64>,
    #[serde(
        rename = "refunds_issued_count",
        skip_serializing_if = "Option::is_none"
    )]
    pub refunds_issued_count: Option<i64>,
    #[serde(
        rename = "refunds_issued_service_charge",
        skip_serializing_if = "Option::is_none"
    )]
    pub refunds_issued_service_charge: Option<i64>,
    /// The tax and service charge inside the refunds issued FROM this till's drawer (`refunds_issued_amount`'s split).
    #[serde(rename = "refunds_issued_tax", skip_serializing_if = "Option::is_none")]
    pub refunds_issued_tax: Option<i64>,
    #[serde(rename = "safe_drops")]
    pub safe_drops: i64,
    #[serde(
        rename = "service_charge_waived_amount",
        skip_serializing_if = "Option::is_none"
    )]
    pub service_charge_waived_amount: Option<i64>,
    /// Table bills whose service charge was removed (`orders:waive_service`), and what those charges came to. Not part of any total.
    #[serde(
        rename = "service_charge_waived_count",
        skip_serializing_if = "Option::is_none"
    )]
    pub service_charge_waived_count: Option<i64>,
    /// Who viewed (and printed) the cash spot report of this till, oldest first. Additive.
    #[serde(rename = "spot_views", skip_serializing_if = "Option::is_none")]
    pub spot_views: Option<Vec<models::TillSpotView>>,
    /// `branches.standard_float`.
    #[serde(rename = "standard_float", skip_serializing_if = "Option::is_none")]
    pub standard_float: Option<i64>,
    #[serde(
        rename = "suggested_safe_drop",
        skip_serializing_if = "Option::is_none"
    )]
    pub suggested_safe_drop: Option<i64>,
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    #[serde(rename = "total_payments")]
    pub total_payments: i64,
    /// Service charge on this till's sales, less what their refunds took back.
    #[serde(
        rename = "total_service_charge",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_service_charge: Option<i64>,
    /// Tax on this till's sales, less the tax their refunds took back (a partial refund takes back its pro-rata share; a voided or fully refunded sale is out altogether). Additive.
    #[serde(rename = "total_tax", skip_serializing_if = "Option::is_none")]
    pub total_tax: Option<i64>,
    #[serde(rename = "total_tips")]
    pub total_tips: i64,
    #[serde(rename = "voided_amount")]
    pub voided_amount: i64,
    #[serde(rename = "shift")]
    pub shift: Box<models::Shift>,
}

impl ShiftReportResponse {
    pub fn new(
        cash_adjustments: i64,
        cash_movements: Vec<models::CashMovementSummaryRow>,
        cash_movements_in: i64,
        cash_movements_net: i64,
        cash_movements_out: i64,
        cash_tips: i64,
        expected_cash: i64,
        net_payments: i64,
        non_cash_tips: i64,
        payment_summary: Vec<models::PaymentSummaryRow>,
        printed_at: chrono::DateTime<chrono::FixedOffset>,
        safe_drops: i64,
        total_payments: i64,
        total_tips: i64,
        voided_amount: i64,
        shift: models::Shift,
    ) -> ShiftReportResponse {
        ShiftReportResponse {
            cash_adjustments,
            cash_in_refunded_sales: None,
            cash_movements,
            cash_movements_in,
            cash_movements_net,
            cash_movements_out,
            cash_tips,
            expected_cash,
            net_payments,
            non_cash_tips,
            payment_summary,
            printed_at,
            refunds_issued_amount: None,
            refunds_issued_cash: None,
            refunds_issued_count: None,
            refunds_issued_service_charge: None,
            refunds_issued_tax: None,
            safe_drops,
            service_charge_waived_amount: None,
            service_charge_waived_count: None,
            spot_views: None,
            standard_float: None,
            suggested_safe_drop: None,
            timezone: None,
            total_payments,
            total_service_charge: None,
            total_tax: None,
            total_tips,
            voided_amount,
            shift: Box::new(shift),
        }
    }
}
