/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Signal : One advisory flag on a ledger row. `params` carries the evidence numbers the client templates into a localized reason; `link` names the fix surface.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Signal {
    /// below_cost | below_target | cost_spike | price_candidate | removal_candidate | recipe_incomplete
    #[serde(rename = "kind")]
    pub kind: String,
    /// Where the fix lives: `pricing` | `studio` | `studio_recipe`.
    #[serde(rename = "link")]
    pub link: String,
    #[serde(rename = "params")]
    pub params: serde_json::Value,
}

impl Signal {
    /// One advisory flag on a ledger row. `params` carries the evidence numbers the client templates into a localized reason; `link` names the fix surface.
    pub fn new(kind: String, link: String, params: serde_json::Value) -> Signal {
        Signal {
            kind,
            link,
            params,
        }
    }
}

