/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Sort {
    #[serde(rename = "dir", skip_serializing_if = "Option::is_none")]
    pub dir: Option<models::Dir>,
    /// A measure id from `measures`.
    #[serde(rename = "measure")]
    pub measure: String,
}

impl Sort {
    pub fn new(measure: String) -> Sort {
        Sort {
            dir: None,
            measure,
        }
    }
}

