/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StaffRequest {
    /// The record a `correction` proposes to fix. `None` for every other kind.
    #[serde(
        rename = "attendance_record_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub attendance_record_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(
        rename = "decided_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub decided_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(
        rename = "decided_by",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub decided_by: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "decision_note",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub decision_note: Option<Option<String>>,
    /// Set for `leave` and `mission`; the span's last day.
    #[serde(
        rename = "end_date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub end_date: Option<Option<chrono::NaiveDate>>,
    /// Start of the excused window. `None` = open to the shift's start.
    #[serde(
        rename = "from_time",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub from_time: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "is_half_day")]
    pub is_half_day: bool,
    /// Whether the excused time is paid. `None` until decided.
    #[serde(
        rename = "is_paid",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_paid: Option<Option<bool>>,
    /// `leave` | `late_arrival` | `early_departure` | `excuse` | `mission`.
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(
        rename = "leave_type_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub leave_type_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "leave_type_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub leave_type_name: Option<Option<String>>,
    #[serde(
        rename = "location",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub location: Option<Option<String>>,
    #[serde(rename = "on_date")]
    pub on_date: chrono::NaiveDate,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(
        rename = "reason",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub reason: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(
        rename = "title",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub title: Option<Option<String>>,
    /// End of the excused window. `None` = open to the shift's end.
    #[serde(
        rename = "to_time",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub to_time: Option<Option<String>>,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
    #[serde(
        rename = "user_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_name: Option<Option<String>>,
}

impl StaffRequest {
    pub fn new(
        created_at: chrono::DateTime<chrono::FixedOffset>,
        id: uuid::Uuid,
        is_half_day: bool,
        kind: String,
        on_date: chrono::NaiveDate,
        org_id: uuid::Uuid,
        status: String,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
        user_id: uuid::Uuid,
    ) -> StaffRequest {
        StaffRequest {
            attendance_record_id: None,
            created_at,
            decided_at: None,
            decided_by: None,
            decision_note: None,
            end_date: None,
            from_time: None,
            id,
            is_half_day,
            is_paid: None,
            kind,
            leave_type_id: None,
            leave_type_name: None,
            location: None,
            on_date,
            org_id,
            reason: None,
            status,
            title: None,
            to_time: None,
            updated_at,
            user_id,
            user_name: None,
        }
    }
}
