/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusInput {
    /// Target line step: \"confirmed\" | \"preparing\" | \"ready\" | \"out_for_delivery\". The teller may jump to ANY of these from any non-terminal state (forward or back); the landed step is stamped and all other step stamps are cleared, and at most one customer WhatsApp fires (the last newly-crossed step that has one).
    #[serde(rename = "status")]
    pub status: String,
}

impl StatusInput {
    pub fn new(status: String) -> StatusInput {
        StatusInput {
            status,
        }
    }
}

