/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StocktakeItem {
    #[serde(rename = "branch_inventory_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub branch_inventory_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "counted_by", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub counted_by: Option<Option<uuid::Uuid>>,
    #[serde(rename = "counted_qty", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub counted_qty: Option<Option<f64>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "expected_qty")]
    pub expected_qty: f64,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "ingredient_name")]
    pub ingredient_name: String,
    #[serde(rename = "note", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub note: Option<Option<String>>,
    #[serde(rename = "org_ingredient_id")]
    pub org_ingredient_id: uuid::Uuid,
    #[serde(rename = "stocktake_id")]
    pub stocktake_id: uuid::Uuid,
    #[serde(rename = "unit")]
    pub unit: String,
    /// Piastres per unit snapshot; `null` ⟺ unknown.
    #[serde(rename = "unit_cost", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unit_cost: Option<Option<i64>>,
    #[serde(rename = "variance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub variance: Option<Option<f64>>,
    /// theft | spoilage | breakage | miscount | supplier_short | transfer_error | other.
    #[serde(rename = "variance_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub variance_reason: Option<Option<String>>,
}

impl StocktakeItem {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, expected_qty: f64, id: uuid::Uuid, ingredient_name: String, org_ingredient_id: uuid::Uuid, stocktake_id: uuid::Uuid, unit: String) -> StocktakeItem {
        StocktakeItem {
            branch_inventory_id: None,
            counted_by: None,
            counted_qty: None,
            created_at,
            expected_qty,
            id,
            ingredient_name,
            note: None,
            org_ingredient_id,
            stocktake_id,
            unit,
            unit_cost: None,
            variance: None,
            variance_reason: None,
        }
    }
}

