/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Stocktake {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    /// Branch label — only populated by the stocktakes list (so the \"All branches\" view can show which branch each stocktake belongs to). Other stocktake endpoints leave it `null`.
    #[serde(rename = "branch_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub branch_name: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "finalized_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub finalized_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "finalized_by", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub finalized_by: Option<Option<uuid::Uuid>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "note", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub note: Option<Option<String>>,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "started_at")]
    pub started_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "started_by")]
    pub started_by: uuid::Uuid,
    #[serde(rename = "started_by_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub started_by_name: Option<Option<String>>,
    #[serde(rename = "status")]
    pub status: String,
}

impl Stocktake {
    pub fn new(branch_id: uuid::Uuid, created_at: chrono::DateTime<chrono::FixedOffset>, id: uuid::Uuid, org_id: uuid::Uuid, started_at: chrono::DateTime<chrono::FixedOffset>, started_by: uuid::Uuid, status: String) -> Stocktake {
        Stocktake {
            branch_id,
            branch_name: None,
            created_at,
            finalized_at: None,
            finalized_by: None,
            id,
            note: None,
            org_id,
            started_at,
            started_by,
            started_by_name: None,
            status,
        }
    }
}

