/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Suggestion {
    /// The gender default decided it: without it someone else would have been suggested (it says so).
    #[serde(rename = "by_default")]
    pub by_default: bool,
    /// 0–100. Low (≤ 40) whenever the gender default decided it.
    #[serde(rename = "confidence")]
    pub confidence: i32,
    #[serde(rename = "date")]
    pub date: chrono::NaiveDate,
    /// Who the suggestion puts on the shift.
    #[serde(rename = "employee_id")]
    pub employee_id: uuid::Uuid,
    #[serde(rename = "employee_name")]
    pub employee_name: String,
    #[serde(
        rename = "end_time",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub end_time: Option<Option<String>>,
    /// Who it takes off it, for a reassignment.
    #[serde(
        rename = "from_employee_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub from_employee_id: Option<Option<uuid::Uuid>>,
    #[serde(
        rename = "from_employee_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub from_employee_name: Option<Option<String>>,
    /// Opaque; send it back to accept or reject.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "reason_args", deserialize_with = "Option::deserialize")]
    pub reason_args: Option<serde_json::Value>,
    /// A core i18n key for the one-line reason, and its arguments.
    #[serde(rename = "reason_key")]
    pub reason_key: String,
    #[serde(rename = "shift_name")]
    pub shift_name: String,
    /// The shift's times that day (a day-scoped block's own, else its default).
    #[serde(
        rename = "start_time",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub start_time: Option<Option<String>>,
    #[serde(rename = "work_shift_id")]
    pub work_shift_id: uuid::Uuid,
}

impl Suggestion {
    pub fn new(
        by_default: bool,
        confidence: i32,
        date: chrono::NaiveDate,
        employee_id: uuid::Uuid,
        employee_name: String,
        id: String,
        reason_args: Option<serde_json::Value>,
        reason_key: String,
        shift_name: String,
        work_shift_id: uuid::Uuid,
    ) -> Suggestion {
        Suggestion {
            by_default,
            confidence,
            date,
            employee_id,
            employee_name,
            end_time: None,
            from_employee_id: None,
            from_employee_name: None,
            id,
            reason_args,
            reason_key,
            shift_name,
            start_time: None,
            work_shift_id,
        }
    }
}
