/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Supplier {
    #[serde(rename = "contact_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contact_name: Option<Option<String>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    #[serde(rename = "phone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phone: Option<Option<String>>,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl Supplier {
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, id: uuid::Uuid, is_active: bool, name: String, org_id: uuid::Uuid, updated_at: chrono::DateTime<chrono::FixedOffset>) -> Supplier {
        Supplier {
            contact_name: None,
            created_at,
            email: None,
            id,
            is_active,
            name,
            org_id,
            phone: None,
            updated_at,
        }
    }
}

