/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TablePosition : One table's geometry in a bulk drag-save. `section_id` lets a drag move a table between sections in the same save.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TablePosition {
    #[serde(rename = "height")]
    pub height: f64,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "pos_x")]
    pub pos_x: f64,
    #[serde(rename = "pos_y")]
    pub pos_y: f64,
    #[serde(rename = "rotation")]
    pub rotation: f64,
    #[serde(rename = "section_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub section_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "width")]
    pub width: f64,
}

impl TablePosition {
    /// One table's geometry in a bulk drag-save. `section_id` lets a drag move a table between sections in the same save.
    pub fn new(height: f64, id: uuid::Uuid, pos_x: f64, pos_y: f64, rotation: f64, width: f64) -> TablePosition {
        TablePosition {
            height,
            id,
            pos_x,
            pos_y,
            rotation,
            section_id: None,
            width,
        }
    }
}

