/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Till {
    #[serde(rename = "branch_id")]
    pub branch_id: uuid::Uuid,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "is_default")]
    pub is_default: bool,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "org_id")]
    pub org_id: uuid::Uuid,
    /// The cash that should be in this drawer at the start of a shift, in minor units. The shift report proposes closing at it (\"leave the float, drop the rest into the safe\"); `None` means the shop has not decided and nothing is proposed.
    #[serde(
        rename = "standard_float",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub standard_float: Option<Option<i32>>,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl Till {
    pub fn new(
        branch_id: uuid::Uuid,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        id: uuid::Uuid,
        is_active: bool,
        is_default: bool,
        name: String,
        org_id: uuid::Uuid,
        updated_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> Till {
        Till {
            branch_id,
            created_at,
            id,
            is_active,
            is_default,
            name,
            org_id,
            standard_float: None,
            updated_at,
        }
    }
}
