/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeseriesPoint {
    #[serde(rename = "discount")]
    pub discount: i64,
    #[serde(rename = "orders")]
    pub orders: i64,
    #[serde(rename = "period")]
    pub period: String,
    #[serde(rename = "revenue")]
    pub revenue: i64,
    #[serde(rename = "revenue_by_method", deserialize_with = "Option::deserialize")]
    pub revenue_by_method: Option<serde_json::Value>,
    #[serde(rename = "tax")]
    pub tax: i64,
    #[serde(rename = "voided")]
    pub voided: i64,
}

impl TimeseriesPoint {
    pub fn new(discount: i64, orders: i64, period: String, revenue: i64, revenue_by_method: Option<serde_json::Value>, tax: i64, voided: i64) -> TimeseriesPoint {
        TimeseriesPoint {
            discount,
            orders,
            period,
            revenue,
            revenue_by_method,
            tax,
            voided,
        }
    }
}

