/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TopReward : One reward, by how often it was claimed in the range.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopReward {
    #[serde(rename = "menu_item_id")]
    pub menu_item_id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    /// Balance spent on it, net of anything given back by a void or refund.
    #[serde(rename = "points")]
    pub points: i64,
    /// Redemption rows (one per covered order line).
    #[serde(rename = "redemptions")]
    pub redemptions: i64,
    /// Units handed over.
    #[serde(rename = "units")]
    pub units: i64,
    /// Minor units of goods given away (what the covered lines were charged).
    #[serde(rename = "value_minor")]
    pub value_minor: i64,
}

impl TopReward {
    /// One reward, by how often it was claimed in the range.
    pub fn new(
        menu_item_id: uuid::Uuid,
        name: String,
        points: i64,
        redemptions: i64,
        units: i64,
        value_minor: i64,
    ) -> TopReward {
        TopReward {
            menu_item_id,
            name,
            points,
            redemptions,
            units,
            value_minor,
        }
    }
}
