/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransfersSyncResponse {
    #[serde(rename = "server_time")]
    pub server_time: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "transfers")]
    pub transfers: Vec<models::TransferView>,
}

impl TransfersSyncResponse {
    pub fn new(server_time: chrono::DateTime<chrono::FixedOffset>, transfers: Vec<models::TransferView>) -> TransfersSyncResponse {
        TransfersSyncResponse {
            server_time,
            transfers,
        }
    }
}

