/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDiscountRequest {
    #[serde(rename = "dtype", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dtype: Option<Option<String>>,
    #[serde(rename = "is_active", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<Option<bool>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "name_translations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name_translations: Option<Option<serde_json::Value>>,
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<i32>>,
}

impl UpdateDiscountRequest {
    pub fn new() -> UpdateDiscountRequest {
        UpdateDiscountRequest {
            dtype: None,
            is_active: None,
            name: None,
            name_translations: None,
            value: None,
        }
    }
}

