/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateStockRequest {
    #[serde(rename = "current_stock", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_stock: Option<Option<f64>>,
    #[serde(rename = "par_max", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub par_max: Option<Option<f64>>,
    #[serde(rename = "par_min", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub par_min: Option<Option<f64>>,
    #[serde(rename = "reorder_threshold", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reorder_threshold: Option<Option<f64>>,
}

impl UpdateStockRequest {
    pub fn new() -> UpdateStockRequest {
        UpdateStockRequest {
            current_stock: None,
            par_max: None,
            par_min: None,
            reorder_threshold: None,
        }
    }
}

