/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpsertAddonOverrideRequest {
    #[serde(rename = "addon_item_id")]
    pub addon_item_id: uuid::Uuid,
    #[serde(rename = "combo_addon_item_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub combo_addon_item_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "ingredient_name")]
    pub ingredient_name: String,
    #[serde(rename = "ingredient_unit")]
    pub ingredient_unit: String,
    #[serde(rename = "org_ingredient_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub org_ingredient_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "quantity_used")]
    pub quantity_used: f64,
    #[serde(rename = "replaces_org_ingredient_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub replaces_org_ingredient_id: Option<Option<uuid::Uuid>>,
    #[serde(rename = "size_label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub size_label: Option<Option<String>>,
}

impl UpsertAddonOverrideRequest {
    pub fn new(addon_item_id: uuid::Uuid, ingredient_name: String, ingredient_unit: String, quantity_used: f64) -> UpsertAddonOverrideRequest {
        UpsertAddonOverrideRequest {
            addon_item_id,
            combo_addon_item_id: None,
            ingredient_name,
            ingredient_unit,
            org_ingredient_id: None,
            quantity_used,
            replaces_org_ingredient_id: None,
            size_label: None,
        }
    }
}

