/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UserRole {
    #[serde(rename = "super_admin")]
    SuperAdmin,
    #[serde(rename = "org_admin")]
    OrgAdmin,
    #[serde(rename = "branch_manager")]
    BranchManager,
    #[serde(rename = "teller")]
    Teller,
    #[serde(rename = "waiter")]
    Waiter,
    #[serde(rename = "kitchen")]
    Kitchen,

}

impl std::fmt::Display for UserRole {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SuperAdmin => write!(f, "super_admin"),
            Self::OrgAdmin => write!(f, "org_admin"),
            Self::BranchManager => write!(f, "branch_manager"),
            Self::Teller => write!(f, "teller"),
            Self::Waiter => write!(f, "waiter"),
            Self::Kitchen => write!(f, "kitchen"),
        }
    }
}

impl Default for UserRole {
    fn default() -> UserRole {
        Self::SuperAdmin
    }
}

