/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WaiterStats : Per-waiter sales split. Only waiter-attributed orders appear (dine-in settled from a waiter's ticket — `orders.waiter_id IS NOT NULL`); direct teller sales and delivery orders are out of scope, so totals here are a subset of the branch overview. `attributed_orders`/`attributed_revenue` on the report envelope let the UI caption that gap.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WaiterStats {
    /// line_items / orders; 0 when the waiter has no non-voided orders.
    #[serde(rename = "avg_items_per_order")]
    pub avg_items_per_order: f64,
    /// Average bill as rung up — a refund does not shrink what was ordered.
    #[serde(rename = "avg_order_value")]
    pub avg_order_value: i64,
    /// Units sold (SUM of order_items.quantity) on this waiter's non-voided orders — the upsell signal behind avg_items_per_order.
    #[serde(rename = "line_items")]
    pub line_items: i64,
    #[serde(rename = "orders")]
    pub orders: i64,
    /// Net of refunds against this waiter's sales.
    #[serde(rename = "revenue")]
    pub revenue: i64,
    #[serde(rename = "voided")]
    pub voided: i64,
    #[serde(rename = "waiter_id")]
    pub waiter_id: uuid::Uuid,
    #[serde(rename = "waiter_name")]
    pub waiter_name: String,
}

impl WaiterStats {
    /// Per-waiter sales split. Only waiter-attributed orders appear (dine-in settled from a waiter's ticket — `orders.waiter_id IS NOT NULL`); direct teller sales and delivery orders are out of scope, so totals here are a subset of the branch overview. `attributed_orders`/`attributed_revenue` on the report envelope let the UI caption that gap.
    pub fn new(
        avg_items_per_order: f64,
        avg_order_value: i64,
        line_items: i64,
        orders: i64,
        revenue: i64,
        voided: i64,
        waiter_id: uuid::Uuid,
        waiter_name: String,
    ) -> WaiterStats {
        WaiterStats {
            avg_items_per_order,
            avg_order_value,
            line_items,
            orders,
            revenue,
            voided,
            waiter_id,
            waiter_name,
        }
    }
}
