/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WidgetOutcome : A widget either produced a result or an explanation. Never both, never neither — and a failure here is a 200 with an `error`, not a failed batch.
/// A widget either produced a result or an explanation. Never both, never neither — and a failure here is a 200 with an `error`, not a failed batch.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WidgetOutcome {
    WidgetOutcomeOneOf(Box<models::WidgetOutcomeOneOf>),
    WidgetOutcomeOneOf1(Box<models::WidgetOutcomeOneOf1>),
}

impl Default for WidgetOutcome {
    fn default() -> Self {
        Self::WidgetOutcomeOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "error")]
    Error,
}

impl Default for Status {
    fn default() -> Status {
        Self::Error
    }
}

