/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WidgetOutcomeOneOf {
    #[serde(rename = "columns")]
    pub columns: Vec<models::Column>,
    #[serde(rename = "facet_by", skip_serializing_if = "Option::is_none")]
    pub facet_by: Option<String>,
    #[serde(rename = "grain")]
    pub grain: models::Grain,
    #[serde(rename = "period")]
    pub period: Box<models::PeriodInfo>,
    #[serde(rename = "row_count")]
    pub row_count: i32,
    #[serde(rename = "rows")]
    pub rows: Vec<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "truncated")]
    pub truncated: bool,
    #[serde(rename = "viz")]
    pub viz: models::Viz,
    #[serde(rename = "status")]
    pub status: Status,
}

impl WidgetOutcomeOneOf {
    pub fn new(columns: Vec<models::Column>, grain: models::Grain, period: models::PeriodInfo, row_count: i32, rows: Vec<std::collections::HashMap<String, serde_json::Value>>, truncated: bool, viz: models::Viz, status: Status) -> WidgetOutcomeOneOf {
        WidgetOutcomeOneOf {
            columns,
            facet_by: None,
            grain,
            period: Box::new(period),
            row_count,
            rows,
            title: None,
            truncated,
            viz,
            status,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ok")]
    Ok,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ok
    }
}

