/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WidgetRequest : One widget in a batch. Exactly one of `preset` or `spec`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WidgetRequest {
    /// Caller-chosen key, echoed back so results can be matched to widgets.
    #[serde(rename = "key")]
    pub key: String,
    /// Overrides the batch-level period for this widget alone.
    #[serde(rename = "period", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub period: Option<Option<Box<models::Period>>>,
    /// A curated metric id from `GET /metrics/schema`.
    #[serde(rename = "preset", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preset: Option<Option<String>>,
    /// A fully custom query. Same IR the AI agent produces.
    #[serde(rename = "spec", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub spec: Option<Option<Box<models::QuerySpec>>>,
}

impl WidgetRequest {
    /// One widget in a batch. Exactly one of `preset` or `spec`.
    pub fn new(key: String) -> WidgetRequest {
        WidgetRequest {
            key,
            period: None,
            preset: None,
            spec: None,
        }
    }
}

