/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`add_to_branch_stock`]
#[derive(Clone, Debug)]
pub struct AddToBranchStockParams {
    /// Branch ID
    pub branch_id: String,
    pub add_to_stock_request: models::AddToStockRequest
}

/// struct for passing parameters to the method [`create_catalog_item`]
#[derive(Clone, Debug)]
pub struct CreateCatalogItemParams {
    /// Organization ID
    pub org_id: String,
    pub create_catalog_item_request: models::CreateCatalogItemRequest
}

/// struct for passing parameters to the method [`create_transfer`]
#[derive(Clone, Debug)]
pub struct CreateTransferParams {
    pub create_transfer_request: models::CreateTransferRequest
}

/// struct for passing parameters to the method [`create_waste`]
#[derive(Clone, Debug)]
pub struct CreateWasteParams {
    /// Branch ID
    pub branch_id: String,
    pub create_waste_request: models::CreateWasteRequest
}

/// struct for passing parameters to the method [`delete_catalog_item`]
#[derive(Clone, Debug)]
pub struct DeleteCatalogItemParams {
    /// Organization ID
    pub org_id: String,
    /// Ingredient ID
    pub id: String
}

/// struct for passing parameters to the method [`delete_transfer`]
#[derive(Clone, Debug)]
pub struct DeleteTransferParams {
    /// Transfer ID
    pub id: String
}

/// struct for passing parameters to the method [`get_inventory_settings`]
#[derive(Clone, Debug)]
pub struct GetInventorySettingsParams {
    /// Organization ID
    pub org_id: String
}

/// struct for passing parameters to the method [`list_branch_stock`]
#[derive(Clone, Debug)]
pub struct ListBranchStockParams {
    /// Branch ID
    pub branch_id: String
}

/// struct for passing parameters to the method [`list_catalog`]
#[derive(Clone, Debug)]
pub struct ListCatalogParams {
    /// Organization ID
    pub org_id: String
}

/// struct for passing parameters to the method [`list_movements`]
#[derive(Clone, Debug)]
pub struct ListMovementsParams {
    /// Branch ID
    pub branch_id: String,
    pub org_ingredient_id: Option<String>,
    pub r#type: Option<String>,
    pub from: Option<chrono::DateTime<chrono::FixedOffset>>,
    pub to: Option<chrono::DateTime<chrono::FixedOffset>>,
    pub page: Option<i64>,
    pub per_page: Option<i64>
}

/// struct for passing parameters to the method [`list_transfers`]
#[derive(Clone, Debug)]
pub struct ListTransfersParams {
    pub branch_id: String,
    pub direction: Option<String>,
    pub limit: Option<i64>,
    pub offset: Option<i64>
}

/// struct for passing parameters to the method [`list_waste`]
#[derive(Clone, Debug)]
pub struct ListWasteParams {
    /// Branch ID
    pub branch_id: String
}

/// struct for passing parameters to the method [`remove_from_branch_stock`]
#[derive(Clone, Debug)]
pub struct RemoveFromBranchStockParams {
    /// Branch ID
    pub branch_id: String,
    /// Stock ID
    pub id: String
}

/// struct for passing parameters to the method [`update_branch_stock`]
#[derive(Clone, Debug)]
pub struct UpdateBranchStockParams {
    /// Branch ID
    pub branch_id: String,
    /// Stock ID
    pub id: String,
    pub update_stock_request: models::UpdateStockRequest
}

/// struct for passing parameters to the method [`update_catalog_item`]
#[derive(Clone, Debug)]
pub struct UpdateCatalogItemParams {
    /// Organization ID
    pub org_id: String,
    /// Ingredient ID
    pub id: String,
    pub update_catalog_item_request: models::UpdateCatalogItemRequest
}

/// struct for passing parameters to the method [`update_inventory_settings`]
#[derive(Clone, Debug)]
pub struct UpdateInventorySettingsParams {
    /// Organization ID
    pub org_id: String,
    pub update_inventory_settings_request: models::UpdateInventorySettingsRequest
}

/// struct for passing parameters to the method [`update_transfer`]
#[derive(Clone, Debug)]
pub struct UpdateTransferParams {
    /// Transfer ID
    pub id: String,
    pub update_transfer_request: models::UpdateTransferRequest
}


/// struct for typed errors of method [`add_to_branch_stock`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddToBranchStockError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_catalog_item`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateCatalogItemError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_transfer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateTransferError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_waste`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateWasteError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_catalog_item`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteCatalogItemError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_transfer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTransferError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_inventory_settings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetInventorySettingsError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_branch_stock`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListBranchStockError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_catalog`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListCatalogError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_movements`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListMovementsError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_transfers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTransfersError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_waste`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListWasteError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`remove_from_branch_stock`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RemoveFromBranchStockError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_branch_stock`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateBranchStockError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_catalog_item`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateCatalogItemError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_inventory_settings`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateInventorySettingsError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_transfer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateTransferError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}


pub async fn add_to_branch_stock(configuration: &configuration::Configuration, params: AddToBranchStockParams) -> Result<models::BranchInventoryItem, Error<AddToBranchStockError>> {

    let uri_str = format!("{}/inventory/branches/{branch_id}/stock", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.add_to_stock_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BranchInventoryItem`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BranchInventoryItem`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AddToBranchStockError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn create_catalog_item(configuration: &configuration::Configuration, params: CreateCatalogItemParams) -> Result<models::OrgIngredient, Error<CreateCatalogItemError>> {

    let uri_str = format!("{}/inventory/orgs/{org_id}/catalog", configuration.base_path, org_id=crate::apis::urlencode(params.org_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.create_catalog_item_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrgIngredient`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrgIngredient`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateCatalogItemError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn create_transfer(configuration: &configuration::Configuration, params: CreateTransferParams) -> Result<models::BranchInventoryTransfer, Error<CreateTransferError>> {

    let uri_str = format!("{}/inventory/transfers", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.create_transfer_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BranchInventoryTransfer`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BranchInventoryTransfer`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateTransferError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn create_waste(configuration: &configuration::Configuration, params: CreateWasteParams) -> Result<models::BranchInventoryMovement, Error<CreateWasteError>> {

    let uri_str = format!("{}/inventory/branches/{branch_id}/waste", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.create_waste_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BranchInventoryMovement`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BranchInventoryMovement`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateWasteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_catalog_item(configuration: &configuration::Configuration, params: DeleteCatalogItemParams) -> Result<(), Error<DeleteCatalogItemError>> {

    let uri_str = format!("{}/inventory/orgs/{org_id}/catalog/{id}", configuration.base_path, org_id=crate::apis::urlencode(params.org_id), id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteCatalogItemError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_transfer(configuration: &configuration::Configuration, params: DeleteTransferParams) -> Result<(), Error<DeleteTransferError>> {

    let uri_str = format!("{}/inventory/transfers/{id}", configuration.base_path, id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTransferError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_inventory_settings(configuration: &configuration::Configuration, params: GetInventorySettingsParams) -> Result<models::OrgInventorySettings, Error<GetInventorySettingsError>> {

    let uri_str = format!("{}/inventory/orgs/{org_id}/settings", configuration.base_path, org_id=crate::apis::urlencode(params.org_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrgInventorySettings`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrgInventorySettings`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetInventorySettingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_branch_stock(configuration: &configuration::Configuration, params: ListBranchStockParams) -> Result<Vec<models::BranchInventoryItem>, Error<ListBranchStockError>> {

    let uri_str = format!("{}/inventory/branches/{branch_id}/stock", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::BranchInventoryItem&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::BranchInventoryItem&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListBranchStockError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_catalog(configuration: &configuration::Configuration, params: ListCatalogParams) -> Result<Vec<models::OrgIngredient>, Error<ListCatalogError>> {

    let uri_str = format!("{}/inventory/orgs/{org_id}/catalog", configuration.base_path, org_id=crate::apis::urlencode(params.org_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::OrgIngredient&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::OrgIngredient&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListCatalogError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_movements(configuration: &configuration::Configuration, params: ListMovementsParams) -> Result<Vec<models::BranchInventoryMovement>, Error<ListMovementsError>> {

    let uri_str = format!("{}/inventory/branches/{branch_id}/movements", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.org_ingredient_id {
        req_builder = req_builder.query(&[("org_ingredient_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.r#type {
        req_builder = req_builder.query(&[("type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::BranchInventoryMovement&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::BranchInventoryMovement&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListMovementsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_transfers(configuration: &configuration::Configuration, params: ListTransfersParams) -> Result<Vec<models::BranchInventoryTransfer>, Error<ListTransfersError>> {

    let uri_str = format!("{}/inventory/branches/{branch_id}/transfers", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.direction {
        req_builder = req_builder.query(&[("direction", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::BranchInventoryTransfer&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::BranchInventoryTransfer&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListTransfersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_waste(configuration: &configuration::Configuration, params: ListWasteParams) -> Result<Vec<models::BranchInventoryMovement>, Error<ListWasteError>> {

    let uri_str = format!("{}/inventory/branches/{branch_id}/waste", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::BranchInventoryMovement&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::BranchInventoryMovement&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListWasteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn remove_from_branch_stock(configuration: &configuration::Configuration, params: RemoveFromBranchStockParams) -> Result<(), Error<RemoveFromBranchStockError>> {

    let uri_str = format!("{}/inventory/branches/{branch_id}/stock/{id}", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id), id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RemoveFromBranchStockError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_branch_stock(configuration: &configuration::Configuration, params: UpdateBranchStockParams) -> Result<models::BranchInventoryItem, Error<UpdateBranchStockError>> {

    let uri_str = format!("{}/inventory/branches/{branch_id}/stock/{id}", configuration.base_path, branch_id=crate::apis::urlencode(params.branch_id), id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.update_stock_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BranchInventoryItem`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BranchInventoryItem`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateBranchStockError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_catalog_item(configuration: &configuration::Configuration, params: UpdateCatalogItemParams) -> Result<models::OrgIngredient, Error<UpdateCatalogItemError>> {

    let uri_str = format!("{}/inventory/orgs/{org_id}/catalog/{id}", configuration.base_path, org_id=crate::apis::urlencode(params.org_id), id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.update_catalog_item_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrgIngredient`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrgIngredient`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateCatalogItemError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_inventory_settings(configuration: &configuration::Configuration, params: UpdateInventorySettingsParams) -> Result<models::OrgInventorySettings, Error<UpdateInventorySettingsError>> {

    let uri_str = format!("{}/inventory/orgs/{org_id}/settings", configuration.base_path, org_id=crate::apis::urlencode(params.org_id));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.update_inventory_settings_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrgInventorySettings`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrgInventorySettings`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateInventorySettingsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn update_transfer(configuration: &configuration::Configuration, params: UpdateTransferParams) -> Result<models::BranchInventoryTransfer, Error<UpdateTransferError>> {

    let uri_str = format!("{}/inventory/transfers/{id}", configuration.base_path, id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.update_transfer_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BranchInventoryTransfer`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BranchInventoryTransfer`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateTransferError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

