/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`create_order`]
#[derive(Clone, Debug)]
pub struct CreateOrderParams {
    pub create_order_request: models::CreateOrderRequest
}

/// struct for passing parameters to the method [`export_orders`]
#[derive(Clone, Debug)]
pub struct ExportOrdersParams {
    pub branch_id: Option<String>,
    pub shift_id: Option<String>,
    pub teller_name: Option<String>,
    /// Filter by the WAITER who opened the ticket (ILIKE, partial match).
    pub waiter_name: Option<String>,
    pub payment_method: Option<String>,
    pub status: Option<String>,
    pub from: Option<chrono::DateTime<chrono::FixedOffset>>,
    pub to: Option<chrono::DateTime<chrono::FixedOffset>>
}

/// struct for passing parameters to the method [`get_order`]
#[derive(Clone, Debug)]
pub struct GetOrderParams {
    /// Order ID
    pub order_id: String
}

/// struct for passing parameters to the method [`list_orders`]
#[derive(Clone, Debug)]
pub struct ListOrdersParams {
    pub branch_id: Option<String>,
    pub shift_id: Option<String>,
    pub updated_after: Option<chrono::DateTime<chrono::FixedOffset>>,
    pub page: Option<i64>,
    pub per_page: Option<i64>,
    pub teller_name: Option<String>,
    /// Filter by the WAITER who opened the ticket (ILIKE, partial match). Matches only orders that carry a waiter (dine-in settled from a waiter's ticket).
    pub waiter_name: Option<String>,
    pub payment_method: Option<String>,
    pub status: Option<String>,
    pub from: Option<chrono::DateTime<chrono::FixedOffset>>,
    pub to: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Filter by order origin: \"dine_in\" or \"delivery\".
    pub order_type: Option<String>,
    /// Filter delivery orders by channel: \"in_mall\" or \"outside\".
    pub channel: Option<String>,
    /// When true, each order in `data` embeds its full line items (addons/optionals/bundle components) — the response shape becomes [PaginatedOrdersFull]. Lets offline-first clients cache complete orders in one round trip instead of fetching each order separately.
    pub include_items: Option<bool>
}

/// struct for passing parameters to the method [`preview_recipe`]
#[derive(Clone, Debug)]
pub struct PreviewRecipeParams {
    pub preview_recipe_request: models::PreviewRecipeRequest
}

/// struct for passing parameters to the method [`void_order`]
#[derive(Clone, Debug)]
pub struct VoidOrderParams {
    /// Order ID
    pub order_id: String,
    pub void_order_request: models::VoidOrderRequest
}


/// struct for typed errors of method [`create_order`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateOrderError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`export_orders`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExportOrdersError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_order`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetOrderError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_orders`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListOrdersError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`preview_recipe`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PreviewRecipeError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`void_order`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VoidOrderError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}


pub async fn create_order(configuration: &configuration::Configuration, params: CreateOrderParams) -> Result<models::OrderFull, Error<CreateOrderError>> {

    let uri_str = format!("{}/orders", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.create_order_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrderFull`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrderFull`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateOrderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn export_orders(configuration: &configuration::Configuration, params: ExportOrdersParams) -> Result<models::ExportResponse, Error<ExportOrdersError>> {

    let uri_str = format!("{}/orders/export", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.branch_id {
        req_builder = req_builder.query(&[("branch_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.shift_id {
        req_builder = req_builder.query(&[("shift_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.teller_name {
        req_builder = req_builder.query(&[("teller_name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.waiter_name {
        req_builder = req_builder.query(&[("waiter_name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.payment_method {
        req_builder = req_builder.query(&[("payment_method", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ExportResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ExportResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ExportOrdersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn get_order(configuration: &configuration::Configuration, params: GetOrderParams) -> Result<models::OrderFull, Error<GetOrderError>> {

    let uri_str = format!("{}/orders/{order_id}", configuration.base_path, order_id=crate::apis::urlencode(params.order_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrderFull`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrderFull`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetOrderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_orders(configuration: &configuration::Configuration, params: ListOrdersParams) -> Result<models::PaginatedOrders, Error<ListOrdersError>> {

    let uri_str = format!("{}/orders", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.branch_id {
        req_builder = req_builder.query(&[("branch_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.shift_id {
        req_builder = req_builder.query(&[("shift_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.updated_after {
        req_builder = req_builder.query(&[("updated_after", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.per_page {
        req_builder = req_builder.query(&[("per_page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.teller_name {
        req_builder = req_builder.query(&[("teller_name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.waiter_name {
        req_builder = req_builder.query(&[("waiter_name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.payment_method {
        req_builder = req_builder.query(&[("payment_method", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.from {
        req_builder = req_builder.query(&[("from", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.to {
        req_builder = req_builder.query(&[("to", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.order_type {
        req_builder = req_builder.query(&[("order_type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.channel {
        req_builder = req_builder.query(&[("channel", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.include_items {
        req_builder = req_builder.query(&[("include_items", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::PaginatedOrders`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::PaginatedOrders`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListOrdersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn preview_recipe(configuration: &configuration::Configuration, params: PreviewRecipeParams) -> Result<Vec<models::PreviewIngredient>, Error<PreviewRecipeError>> {

    let uri_str = format!("{}/orders/preview-recipe", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.preview_recipe_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::PreviewIngredient&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::PreviewIngredient&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PreviewRecipeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn void_order(configuration: &configuration::Configuration, params: VoidOrderParams) -> Result<models::Order, Error<VoidOrderError>> {

    let uri_str = format!("{}/orders/{order_id}/void", configuration.base_path, order_id=crate::apis::urlencode(params.order_id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.void_order_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Order`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::Order`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<VoidOrderError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

