/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};

/// struct for passing parameters to the method [`branch_qr`]
#[derive(Clone, Debug)]
pub struct BranchQrParams {
    /// Branch ID
    pub id: String,
    /// `true` (default) → branded A6 card PNG; `false` → plain receipt QR PNG.
    pub card: Option<bool>,
    /// Dynamic caption line beneath the tagline (A6 card only).
    pub caption: Option<String>,
    /// Raster DPI for the A6 card (clamped 72–2400). Default 600.
    pub dpi: Option<u32>,
    /// Print bleed in mm (A6 card only). Default 0.
    pub bleed_mm: Option<f32>,
    /// Draw crop marks (A6 card, only meaningful when `bleed_mm > 0`).
    pub crop_marks: Option<bool>,
    /// Return the A6 card as SVG (`data:image/svg+xml;base64,…`). Default false.
    pub svg: Option<bool>,
    /// Pixels per module for the plain receipt QR (1–40). Default 16.
    pub module_px: Option<u32>,
    pub slug: Option<String>,
    /// Shop or company name inside the mall (e.g. \"Starbucks Kiosk 3\").
    pub place_name: Option<String>,
    /// Floor (e.g. \"Ground Floor\").
    pub floor: Option<String>,
    /// Unit or office number (e.g. \"Unit 42\").
    pub unit_number: Option<String>
}

/// struct for passing parameters to the method [`create_marketing_link`]
#[derive(Clone, Debug)]
pub struct CreateMarketingLinkParams {
    pub create_marketing_link_request: models::CreateMarketingLinkRequest
}

/// struct for passing parameters to the method [`create_table`]
#[derive(Clone, Debug)]
pub struct CreateTableParams {
    /// Branch ID
    pub id: String,
    pub create_table_request: models::CreateTableRequest
}

/// struct for passing parameters to the method [`delete_table`]
#[derive(Clone, Debug)]
pub struct DeleteTableParams {
    /// Branch ID
    pub id: String,
    /// Table ID
    pub tid: String
}

/// struct for passing parameters to the method [`delivery_order_qr`]
#[derive(Clone, Debug)]
pub struct DeliveryOrderQrParams {
    /// Delivery order ID
    pub id: String,
    /// `true` (default) → branded A6 card PNG; `false` → plain receipt QR PNG.
    pub card: Option<bool>,
    /// Dynamic caption line beneath the tagline (A6 card only).
    pub caption: Option<String>,
    /// Raster DPI for the A6 card (clamped 72–2400). Default 600.
    pub dpi: Option<u32>,
    /// Print bleed in mm (A6 card only). Default 0.
    pub bleed_mm: Option<f32>,
    /// Draw crop marks (A6 card, only meaningful when `bleed_mm > 0`).
    pub crop_marks: Option<bool>,
    /// Return the A6 card as SVG (`data:image/svg+xml;base64,…`). Default false.
    pub svg: Option<bool>,
    /// Pixels per module for the plain receipt QR (1–40). Default 16.
    pub module_px: Option<u32>
}

/// struct for passing parameters to the method [`list_tables`]
#[derive(Clone, Debug)]
pub struct ListTablesParams {
    /// Branch ID
    pub id: String
}

/// struct for passing parameters to the method [`org_qr`]
#[derive(Clone, Debug)]
pub struct OrgQrParams {
    /// Organisation ID
    pub id: String,
    /// `true` (default) → branded A6 card PNG; `false` → plain receipt QR PNG.
    pub card: Option<bool>,
    /// Dynamic caption line beneath the tagline (A6 card only).
    pub caption: Option<String>,
    /// Raster DPI for the A6 card (clamped 72–2400). Default 600.
    pub dpi: Option<u32>,
    /// Print bleed in mm (A6 card only). Default 0.
    pub bleed_mm: Option<f32>,
    /// Draw crop marks (A6 card, only meaningful when `bleed_mm > 0`).
    pub crop_marks: Option<bool>,
    /// Return the A6 card as SVG (`data:image/svg+xml;base64,…`). Default false.
    pub svg: Option<bool>,
    /// Pixels per module for the plain receipt QR (1–40). Default 16.
    pub module_px: Option<u32>
}

/// struct for passing parameters to the method [`table_qr`]
#[derive(Clone, Debug)]
pub struct TableQrParams {
    /// Branch ID
    pub id: String,
    /// Table ID
    pub tid: String,
    /// `true` (default) → branded A6 card PNG; `false` → plain receipt QR PNG.
    pub card: Option<bool>,
    /// Dynamic caption line beneath the tagline (A6 card only).
    pub caption: Option<String>,
    /// Raster DPI for the A6 card (clamped 72–2400). Default 600.
    pub dpi: Option<u32>,
    /// Print bleed in mm (A6 card only). Default 0.
    pub bleed_mm: Option<f32>,
    /// Draw crop marks (A6 card, only meaningful when `bleed_mm > 0`).
    pub crop_marks: Option<bool>,
    /// Return the A6 card as SVG (`data:image/svg+xml;base64,…`). Default false.
    pub svg: Option<bool>,
    /// Pixels per module for the plain receipt QR (1–40). Default 16.
    pub module_px: Option<u32>
}


/// struct for typed errors of method [`branch_qr`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BranchQrError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_marketing_link`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateMarketingLinkError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_table`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateTableError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_table`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteTableError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delivery_order_qr`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeliveryOrderQrError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_marketing_links`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListMarketingLinksError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_tables`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListTablesError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`org_qr`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrgQrError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`table_qr`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TableQrError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}


pub async fn branch_qr(configuration: &configuration::Configuration, params: BranchQrParams) -> Result<models::QrResponse, Error<BranchQrError>> {

    let uri_str = format!("{}/branches/{id}/qr", configuration.base_path, id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.card {
        req_builder = req_builder.query(&[("card", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.caption {
        req_builder = req_builder.query(&[("caption", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.dpi {
        req_builder = req_builder.query(&[("dpi", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.bleed_mm {
        req_builder = req_builder.query(&[("bleed_mm", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.crop_marks {
        req_builder = req_builder.query(&[("crop_marks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.svg {
        req_builder = req_builder.query(&[("svg", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.module_px {
        req_builder = req_builder.query(&[("module_px", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.slug {
        req_builder = req_builder.query(&[("slug", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.place_name {
        req_builder = req_builder.query(&[("place_name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.floor {
        req_builder = req_builder.query(&[("floor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.unit_number {
        req_builder = req_builder.query(&[("unit_number", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::QrResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::QrResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<BranchQrError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn create_marketing_link(configuration: &configuration::Configuration, params: CreateMarketingLinkParams) -> Result<models::QrResponse, Error<CreateMarketingLinkError>> {

    let uri_str = format!("{}/qr/links", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.create_marketing_link_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::QrResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::QrResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateMarketingLinkError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn create_table(configuration: &configuration::Configuration, params: CreateTableParams) -> Result<models::BranchTable, Error<CreateTableError>> {

    let uri_str = format!("{}/branches/{id}/tables", configuration.base_path, id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.create_table_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BranchTable`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::BranchTable`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateTableError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delete_table(configuration: &configuration::Configuration, params: DeleteTableParams) -> Result<(), Error<DeleteTableError>> {

    let uri_str = format!("{}/branches/{id}/tables/{tid}", configuration.base_path, id=crate::apis::urlencode(params.id), tid=crate::apis::urlencode(params.tid));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteTableError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn delivery_order_qr(configuration: &configuration::Configuration, params: DeliveryOrderQrParams) -> Result<models::QrResponse, Error<DeliveryOrderQrError>> {

    let uri_str = format!("{}/delivery-orders/{id}/qr", configuration.base_path, id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.card {
        req_builder = req_builder.query(&[("card", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.caption {
        req_builder = req_builder.query(&[("caption", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.dpi {
        req_builder = req_builder.query(&[("dpi", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.bleed_mm {
        req_builder = req_builder.query(&[("bleed_mm", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.crop_marks {
        req_builder = req_builder.query(&[("crop_marks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.svg {
        req_builder = req_builder.query(&[("svg", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.module_px {
        req_builder = req_builder.query(&[("module_px", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::QrResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::QrResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<DeliveryOrderQrError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_marketing_links(configuration: &configuration::Configuration) -> Result<Vec<models::MarketingLink>, Error<ListMarketingLinksError>> {

    let uri_str = format!("{}/qr/links", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::MarketingLink&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::MarketingLink&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListMarketingLinksError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn list_tables(configuration: &configuration::Configuration, params: ListTablesParams) -> Result<Vec<models::BranchTable>, Error<ListTablesError>> {

    let uri_str = format!("{}/branches/{id}/tables", configuration.base_path, id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::BranchTable&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::BranchTable&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListTablesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn org_qr(configuration: &configuration::Configuration, params: OrgQrParams) -> Result<models::QrResponse, Error<OrgQrError>> {

    let uri_str = format!("{}/orgs/{id}/qr", configuration.base_path, id=crate::apis::urlencode(params.id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.card {
        req_builder = req_builder.query(&[("card", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.caption {
        req_builder = req_builder.query(&[("caption", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.dpi {
        req_builder = req_builder.query(&[("dpi", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.bleed_mm {
        req_builder = req_builder.query(&[("bleed_mm", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.crop_marks {
        req_builder = req_builder.query(&[("crop_marks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.svg {
        req_builder = req_builder.query(&[("svg", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.module_px {
        req_builder = req_builder.query(&[("module_px", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::QrResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::QrResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrgQrError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn table_qr(configuration: &configuration::Configuration, params: TableQrParams) -> Result<models::QrResponse, Error<TableQrError>> {

    let uri_str = format!("{}/branches/{id}/tables/{tid}/qr", configuration.base_path, id=crate::apis::urlencode(params.id), tid=crate::apis::urlencode(params.tid));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.card {
        req_builder = req_builder.query(&[("card", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.caption {
        req_builder = req_builder.query(&[("caption", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.dpi {
        req_builder = req_builder.query(&[("dpi", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.bleed_mm {
        req_builder = req_builder.query(&[("bleed_mm", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.crop_marks {
        req_builder = req_builder.query(&[("crop_marks", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.svg {
        req_builder = req_builder.query(&[("svg", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.module_px {
        req_builder = req_builder.query(&[("module_px", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::QrResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::QrResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<TableQrError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

