/*
 * Madar API
 *
 * Madar POS — multi-tenant cafe and restaurant management. The Rust backend is the source of truth for this spec; the Flutter teller app and React management dashboard consume the generated openapi.json.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`create_refund`]
#[derive(Clone, Debug)]
pub struct CreateRefundParams {
    pub create_refund_request: models::CreateRefundRequest,
}

/// struct for passing parameters to the method [`get_refund`]
#[derive(Clone, Debug)]
pub struct GetRefundParams {
    /// Refund ID
    pub id: String,
}

/// struct for passing parameters to the method [`list_order_refunds`]
#[derive(Clone, Debug)]
pub struct ListOrderRefundsParams {
    /// Order ID
    pub order_id: String,
}

/// struct for passing parameters to the method [`list_shift_refunds`]
#[derive(Clone, Debug)]
pub struct ListShiftRefundsParams {
    /// Shift ID
    pub shift_id: String,
}

/// struct for typed errors of method [`create_refund`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateRefundError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_refund`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRefundError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_order_refunds`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListOrderRefundsError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_shift_refunds`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListShiftRefundsError {
    Status400(models::ErrorBody),
    Status401(models::ErrorBody),
    Status403(models::ErrorBody),
    Status404(models::ErrorBody),
    Status409(models::ErrorBody),
    Status500(models::ErrorBody),
    UnknownValue(serde_json::Value),
}

pub async fn create_refund(
    configuration: &configuration::Configuration,
    params: CreateRefundParams,
) -> Result<models::RefundIssued, Error<CreateRefundError>> {
    let uri_str = format!("{}/refunds", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.create_refund_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RefundIssued`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RefundIssued`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateRefundError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_refund(
    configuration: &configuration::Configuration,
    params: GetRefundParams,
) -> Result<models::RefundFull, Error<GetRefundError>> {
    let uri_str = format!(
        "{}/refunds/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(params.id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::RefundFull`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::RefundFull`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetRefundError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn list_order_refunds(
    configuration: &configuration::Configuration,
    params: ListOrderRefundsParams,
) -> Result<models::OrderRefunds, Error<ListOrderRefundsError>> {
    let uri_str = format!(
        "{}/refunds/order/{order_id}",
        configuration.base_path,
        order_id = crate::apis::urlencode(params.order_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrderRefunds`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrderRefunds`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListOrderRefundsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn list_shift_refunds(
    configuration: &configuration::Configuration,
    params: ListShiftRefundsParams,
) -> Result<models::ShiftRefunds, Error<ListShiftRefundsError>> {
    let uri_str = format!(
        "{}/refunds/shift/{shift_id}",
        configuration.base_path,
        shift_id = crate::apis::urlencode(params.shift_id)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ShiftRefunds`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ShiftRefunds`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListShiftRefundsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
